### ISSUE TITLE
[REQ] Protecting Sequal Pro with password

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1145]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1145
Reporter:mtro...@gmail.com Date:2011-08-08 11:32:13 Status:WontFix Closed:2011-08-01

Hi,

It would be very cool, if you could protect sequel pro with a password.

I have many connections that may not fall into the wrong hands - e.g. if a person steals my computer.
So I don't want to use the connections favorites to store my passwords.

But if you could protect Sequal Pro with a password, so you cannot use a favorite connection without entering your OS X password e.g Or maybe even can start sequel pro without entering mac os x password (or a password set in the sequel pro settings).

Would be cool :o)

**Comment by maxisme** [comment]
+1 I find the issue is that they can still alter my databases even if the password is protected by keychain. Some sort of timeout password would be great!

**Comment by abhibeckert** [comment]
@maxisme you can already do this.

Just open Keychain Access, search for "Sequel Pro" and double click on the password you need extra protection for.

Under access control you can set your keychain password to be required every time and you can remove Sequel Pro from the "Always allow access" list.

Once that's done you'll be asked to enter your keychain password every time you connect. Be sure to select "allow once" instead of "allow always".
