### ISSUE TITLE
Cannot select public keys that are in subdirectories of ~/.ssh

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1176]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1176
Reporter:lnightin...@gmail.com Date:2011-09-06 06:45:13 Status:Implemented Closed:2011-09-01

<b>What steps will reproduce the problem?</b>
1.click on the &quot;key&quot; icon in the connection dialog box for an SSH connection
2.a &quot;finder&quot; window is opened, but it does not allow access to the ~/.ssh directory
3.my keys are in ~/.ssh/a_subdirectory/id_rsa and I can't get there to select them

<b>What is the expected output? What do you see instead?</b>
expect to see ~/.ssh as an available location from which to select the keys.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>

<b>Please provide any additional information below.</b>
Sequel Pro is checking ~/.ssh for keys, but not subdirectories. I have my keys organized in subdirectories to keep keys for different locations separate.

**Comment by Arcitec** [comment]
> When I started using subdirectories under ~/.ssh , ssh itself could not find the keys just from the config file. In order to establish an ssh connection, I have to do this: `eval ssh-agent; ssh-add path/to/.ssh/subdirectory/id_rsa`
> 
> then ssh can find the keys. It's possible that there's some problem with my setup, but after a fair amount of research this was the best I could come up with...

Hey, I ran into the same issue. After some research, I can confirm that the problem with subfolders not being scanned is:

1. Intentional by the OpenSSH team.
2. Not a bug

The `ssh-agent` and all the other SSH tools scan for keys in `~/.ssh` but never any subfolders.

You can verify this behavior easily:

```
mkdir ~/.ssh/testfolder
ssh-keygen # give it the path /home/yourname/.ssh/testfolder/id_rsa_test
ssh-add -l # list keys. your new key is not listed
mv ~/.ssh/testfolder/id_rsa_test* ~/.ssh/
ssh-add -l # list keys, it is now listed since it's in the correct folder.
```

So the conclusion is:

## **NEVER store SSH keys in subfolders. The SSH tools don't support it by default, so you'll have to manually start `ssh-agent` and register the keys with `ssh-add` in each new session.**

Keep the keys inside `~/.ssh` without subfolders as intended instead. That is the only path which allows the SSH tools to automatically register and use the keys.

My own personal strategy for separating keys is to add a suffix with a description of the host or key purpose. Like this:

```
~/.ssh/config
~/.ssh/id_ed25519.storagebox
~/.ssh/id_ed25519.storagebox.pub
~/.ssh/id_rsa.mygithub
~/.ssh/id_rsa.mygithub.pub
~/.ssh/known_hosts
```

This keeps keys cleanly separated alphabetically and also provides info about the type of each key at a glance.

So that's what I do instead of using subfolders!
