### ISSUE TITLE
Number of rows in table information incorrect

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1191]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1191
Reporter:modemmon...@gmail.com Date:2011-09-14 08:41:41 Status:WontFix Closed:2011-09-01

I've only noticed this happening on tables that are relatively large--maybe 100,000+ rows.

I would expect to see the same value as would be returned by a SELECT COUNT query on the table, but instead I see some number that's usually reasonably close, but not actually the correct number. If you hit the refresh button, it'll produce another seemingly random number (keep clicking refresh and you'll keep getting different numbers).

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
Sequel Pro: 0.9.9.1, MySQL: 5.1.5

**Comment by xtaje** [comment]
Aside from being undocumented, it's not clear what the ~ means, and because the UI displays single digit precision, it implies that an exact count (e.g. 15,453,342). To make this obvious, it would be better to round it off and present this as something like `~15.5 million`, or `15.5 million +- 0.5 million`, etc.
