### ISSUE TITLE
When the list of records fills the full page, the last record is mostly covered by the horizontal scrollbar

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1222]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1222
Reporter:jtrap...@gmail.com Date:2011-11-01 07:15:55 Status:OpinionPoll

<b>What steps will reproduce the problem?</b>
1. Fill a table with data that will cause the the window to scroll both horizontally and vertically
2. Scroll to the bottom of the table area
3. Look at the last record and hover mouse on it. The horizontal scroll bar should appear covering most of the record.

<b>What is the expected output? What do you see instead?</b>

Some spacing at the bottom of the table to always keep the records above the very bottom would fix.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>

Sequel Pro: 0.9.9.1

<b>Please provide any additional information below.</b>

**Comment by DaveEP123** [comment]
I'm also now experiencing this problem since upgrading SequelPro, don't remember having the problem before.  I need to click on the last record and edit some fields but can't because of the scroll bar.  This makes s/p pretty unusable without temporarily duplicating that row and inserting a fake row beneath it, which is less than desirable, especially on a live server.

Any update on getting this fixed?
