### ISSUE TITLE
On the localhost/socket issue again

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1356]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1356
Reporter:schlabbe...@gmail.com Date:2012-05-28 13:53:45 Status:New

Currently when a user enters &quot;localhost&quot; in the host field while using &quot;TCP/IP&quot; we try to educate them that it will be interpreted differently.

There are however two issues here:
- It's not really &quot;Mac-like&quot; to educate a user to what he is doing wrong
- This seems to actually cause more confusion among users (&quot;But that works in client XYZ!&quot;)

So I suggest the following:
- The mysql client libs allow to specify an explicit connection method (MYSQL_OPT_PROTOCOL) which when set to TCP/IP will force &quot;localhost&quot; via TCP/IP, too. This solves the dialog for TCP/IP connections.
- For Socket connections there is no issue
- Remains SSH. There are two possible pitfalls when connecting to &quot;localhost&quot;:
  - The server has --skip-networking so it won't respond at all
  - The server has --skip-name-resove so &quot;user@localhost&quot; and &quot;user@127.0.0.1&quot; will be different users and the user will get a permission denied error.

There is no ideal solution to those issues, but we could do a bit of guesswork:
- In case of skip networking we already show a helpful message
- In the other case we can check what mysql reports as host in &quot;Access denied for user 'a'@'b' (using password: YES)&quot;. For example a server with name resolving will show &quot;localhost&quot; while a server without would show &quot;127.0.0.1&quot; (However that is not reliable as e.g. the mysql host could be different from the SSH host and private VPN IPs usually do not resolve to a name)

**Comment by bajax** [comment]
I've run into this same issue.  I have to bind MySQL to a local, non-public interface address on one of our production servers, and not to the public interface.  MySQL either binds to all interfaces or only one interface, so I can't bind it also to our private, secured public IP address.  All of this means that if I want to access it from outside the private network, I have to tunnel through SSH and then connect to the instance proper via socket..  On the other clients I've used (HeidiSQL, Workbench) I just set up my SSH tunnel, set the hostname to 'localhost' so that the remote SQL client we're proxying to interprets it correctly, and away we go.

Please just remove this warning/settings enforcement on the SSH tunnel config screen--with SQL via SSH, all bets are off and you can't make assumptions.  Don't try to handhold when people know exactly what they're doing.  Or, if you can justify the interface clutter, add a "Socket via SSH" option.

**Comment by hoylen** [comment]
Maybe the solution is to change the connection dialog. Instead of having a single text field for "Host", it can have two radio buttons: "TCP network connection" and "MySQL direct socket connection". The first is selected by default. If the first is selected, a text box for the the hostname is available for the user to enter it. If the second is selected, the text box is disabled and not used. This makes it very clear what the options are, and gives the user explicit control over exactly how the connection is performed. The user can choose to type "127.0.0.1" or "localhost" into the text box, or select the "MySQL direct socket connection" to choose between the three different local modes.

Note: I actually find the current dialog box very confusing because of the overloaded term "socket". Since I'm using "localhost" to connect to a local port that is a SSH tunnel to the remote database, I keep thinking "socket" means "TCP/IP sockets" and have to re-read it every time... and then tell myself, "yes, I want to connect over a network socket, but don't click the 'connect via socket' button."

**Comment by abhibeckert** [comment]
@hoylen I want to look into removing socket connections completely, or at least hiding them.

As far as I know, everybody uses (or at least can use) TCP for connecting to their mac, and sockets don't work if we ever enable sandboxing (this is the only feature that can't be done if we sandbox).

**Comment by hoylen** [comment]
Sounds good to me. I can't speak for others, but I certainly don't ever use sockets.

**Comment by gavinanderegg** [comment]
I'd love for there to be a "please just use localhost anyway" option. The hosting company A Small Orange refuses to grant '127.0.0.1' as a connection option, so I can't tunnel in over SSH. So far as I can tell, everything would work well if I could just specify "localhost" instead.

**Comment by dmoagx** [comment]
@gavinanderegg 
That won't help you in any way. If your webhost doesn't allow "127.0.0.1" this most likely means they have disabled TCP/IP connections in which case SSH tunneling would never work anyway (except in the future maybe - see #2054).
Also, even if Sequel Pro did allow "localhost" this has absolutely no effect on the MySQL server as _the remote server never sees what you set as the Host on your local machine_.

A lot of people here seem to misunderstand what this issue is about:
This is not about a bug or a missing feature in Sequel Pro, it's about an inherent design decision of the MySQL permission model and the security policy of the DBA. 
**There is nothing that can be done about that**, we are simply discussing how we can present that fact to the user.

**Comment by gavinanderegg** [comment]
@dmoagx I honestly don't understand the way MySQL connections work under the covers, so I'll take your word on this. It is a very confusing issue.

Just some points on this, even if they're superfluous. The host in question does allow TCP/IP connections, but the `mysql.user` table only accepts connections from `@localhost`. This is why I assumed I could make this work if I could only put `localhost` in the connection info. I can get a straight-up TCP/IP connection working, but I'm not interested in it, as the host only offers it unsecured.

As it turns out, they don't allow SSH tunnelling at all, which is the bigger issue. They also mention MySQL everywhere in their documentation, but actually use Maria DB behind the scenes, which makes me slightly nervous.

Anyway, rant over. Thanks for the swift response!

**Comment by bajax** [comment]
@gavinanderegg You'll need to talk to your host, see if they offer some higher tier of service that does what you want it to.

It sounds like they have the permissions set to not allow root access from outside their systems. There's almost certainly a good reason for that.  

If you want more flexibility, you're probably better off ditching the VPS and going to AWS or Rackspace or something similar, where you have full control over the operating system on your virtual servers.

**Comment by bajax** [comment]
Also, MariaDB is a fork of MySQL, built to be an exact drop-in replacement with some additional features.  It's safe to use anywhere you'd use MySQL.

**Comment by abhibeckert** [comment]
> [MariaDB] is safe to use anywhere you'd use MySQL.

Version 5.x is safe. Version 10.x might not be, we haven't done thorough testing.
