### ISSUE TITLE
Default value for ENUM type

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1383]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1383
Reporter:xch...@broadbandtvcorp.com Date:2012-06-25 16:35:53 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Edit on GUI
2. Add an ENUM type
3. Uncheck &quot;allow null&quot;

<b>What is the expected output? What do you see instead?</b>
An error dialog jumped, because default value '' is not in ENUM. But I don't need a default value.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
0.9.9.1, 
5.5.9

<b>Please provide any additional information below.</b>

**Comment by e404** [comment]
This bug is already two years old. I've run into that several times, and this bug is very annoying.

As noted above, setting NO default value and NOT permitting NULL can be a very handy thing. For example, if you want to force the input of that field, if not supplied, the whole insert would fail. In many occasions, this is exactly what I want.

Just add a simple switch to the code: IF ( type == ENUM ) AND ( ! allow null ) AND ( default value == '' ) >> omit DEFAULT ''

Easily fixed.
Please consider this bug fix.
Priority-Low is completely wrong, it's a serious bug, in my honest opinion.

**Comment by dmoagx** [comment]
This has priority low, because an easy workaround exists (as mentioned in https://github.com/sequelpro/sequelpro/issues/1383#issuecomment-28119291 )

**Comment by e404** [comment]
Also, an easy fix exists ;-)
Thank you for your work though. Highly appreciate it.
Cheers

**Comment by xingshou** [comment]
I cannot understand why this kind of trivial bug is not fixed for 3 to 4 years.
I am very annoyed with this error.
Please fix this error as soon as possible!
