### ISSUE TITLE
Constant crashes for entire app on tab hitting wait timeout

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1597]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1597
Reporter:aradapi...@gmail.com Date:2013-02-06 10:40:08 Status:Invalid Closed:2013-06-21

<b>What steps will reproduce the problem?</b>
this new version constantly pops up disconnect notices (from wait timeout or a legitimate disconnect) which is an annoyance, as it grabs focus to every tab in a long sequence, and then it always crashes after that, so you lose the tab you were working in.  pretty much unusable because of this.

What is the expected output?  stay open and don't pop anything up.  if it disconnects, leave it, if i try to use a disconnected tab, auto reconnect would be nice (like all other clients) but if you must have a pop up at least wait until then.
What do you see instead?  grabs focus to every tab in sequence, which takes forever, then crashes and I lose my work.

What version of Sequel Pro are you using? 1.0.1
What version of OS X are you using? 10.7.5
What version of MySQL are you connecting to on the server? All sorts, not relevant to this.  4.0-5.5, but mostly 5.1.x

<b>Please provide any additional information below.</b>

**Comment by ezmicken** [comment]
I'm having an issue similar to this. Whenever a tab loses connection the entire application is unresponsive until the request(s) times out. If it is the only tab then the whole application closes. In my particular case the tunnel is using  a google cloud proxy on a virtual machine and sequelpro is running in the host. Whenever I wake the host up from sleep none of the connections work and i end up having to wait for each connection to time out in series.

I'd really like to be able to interrupt this process and manually re-establish any connections. The reconnect button never works but i'm sure that's because of the tunneling.
