### ISSUE TITLE
Limit results for custom queries

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1715]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1715
Reporter:leonid.p...@limos.com Date:2013-05-09 09:39:06 Status:WontFix Closed:2013-05-09

<b>What steps will reproduce the problem?</b>
1. Click on Sequel Pro
2. Go to preferences
3. Set &quot;limit results to&quot; 100 rows
4. Run a query that you know will results more than 100 rows eg. select \* from users; 

<b>What is the expected output?</b>
Number of rows should be limited to whatever the limit number is set to in preference
<b>What do you see instead?</b>
all rows being returned

<b>What version of Sequel Pro are you using?</b>
1.0.2 build 4096
<b>What version of OS X are you using?</b>
10.8.3
<b>What version of MySQL are you connecting to on the server?</b>
5.5 and 5.1

<b>Please provide any additional information below.</b>

**Comment by ehongyu** [comment]
I've run into this issue from time to time as well since we are dealing with lots of data and I don't always remember to add "limit" clause to my question.

**Comment by hardeverick** [comment]
Is this up for discussion? Our company is moving away from MySQL Workbench (too many bugs) and Sequel Pro is great, but since we deal with a lot of data (5 Million and 12 Million record tables) we don't want to lock the db because we forgot to put a limit.
Since Workbench did this for us we are used to it. So this is my vote to having this feature even if there's no paging for the data.

**Comment by abhibeckert** [comment]
I agree, this would be a good feature to have.

**Comment by abhibeckert** [comment]
@hardeverick in the mean time... to cancel the query hit `Cmd-Shift-T` (new tab with current connection details) then select the `Database -> Show Server Processes...` menu item.

From there you can select the `select *` query and right click to kill it (due to a UI glitch you have to select first, then right click).

**Comment by ouewqa** [comment]
Does this feature in the development? @abhibeckert @sequelpro
