### ISSUE TITLE
[REQ] Database selection text input / search

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1857]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1850
Reporter: b...@buzelac.com Date: 2013-11-12

I would like the ability to replace the "Select Database" dropdown with a text input (or search box).

When I attempt to connect to a server with many (thousands) of databases, SP locks up. I believe this is because SP is trying to generate a list of all my databases.

Even if I could connect though, I do not want to scroll through thousands of databases. :)

**Comment by monkeyphysics** [comment]
Just duplicated some rows again :)
I'd vote for CTRL + SHIFT + D too.

**Comment by dmoagx** [comment]
So, I thought about it for a bit and have now assigned "cmd+shift+D" to goto and removed it from the database dropdown.

The two additional items in the dropdown have their own keyboard shortcuts, so the only "disadvantage" the goto dialog has, is that it doesn't prioritize and separate the mysql internal databases, which I think is an OK tradeoff and we could improve that in the future if someone complains ;-)

**Comment by chassteel** [comment]
cmd+shift+D works well.  Thanks for making that an option.  The only thing I noticed is that whereas your original Go to Database dialog searched for *all* characters in the search string, the current nightly build searches for *any* characters in the search string.  

I'd vote for a return to the original functionality so that a search of "abc" will return "abc_schema" but not "a_schema_bc".

**Comment by abhibeckert** [comment]
> I'd vote for a return to the original functionality so that a search of "abc" will return "abc_schema" but not "a_schema_bc".

A better solution is just to show matches sorted by their length – abc_schema is 1 character shorter than a_schema_bc and therefore it would be the first suggestion.

I've done tons of research and it turns out sorting by length is an extremely effective way of making the most likely result appear at the top of the list.

**Comment by dmoagx** [comment]
I changed it in the first place to match the behavior of other tools (Xcode, Dash, IntelliJ) as I think it will be more useful that way: Often you have a list of things with a common prefix, e.g.
```
foo_dev
foo_test
foo_prod
bar_dev
bar_test
bar_prod
...
```
In the past to get to `foo_dev` you would have to type `foo_d` (or `o_d`) whereas now you can just type  `fd` to get that item.

One alternative might be to count the match groups and sort by that, ie. `abc` to `abc_schema` is only 1 match group, but `a_schema_bc` is 2. The more groups the less likely it is the desired result.

**Comment by chassteel** [comment]
I imagine this functionality it too obscure for a preference, but a sort by match groups is a good idea.  I use this function practically every time I start the program as I have a ton of databases, so being able to type abc<enter> and get abc_schema as the top hit would be perfect.

**Comment by monkeyphysics** [comment]
I've found the sorting in the dialog can be quite off sometimes. In this example, the selected item should definitely appear first?

![sorting-bug](https://cloud.githubusercontent.com/assets/75087/10022067/4c69a228-614b-11e5-8ab6-6103f13c08a6.png)

**Comment by dmoagx** [comment]
@monkeyphysics Type in "_457" (including the quotes)

I'll look into other optimizations...
