### ISSUE TITLE
Restoring SSH connection using an SSH key with a passphrase causes a freeze

### ISSUE THREAD

**Issue by deanc** [sequelpro/sequelpro#1872]
Steps to reproduce (it happens 9/10 times for me, but not always):
- Create an SSH connection to a remote MySQL server using SSH keys
- Enter your SSH key passphrase
- Connection successful
- Put your mac to sleep
- Wake it up
- Sequel pro will try to reconnect and ass you for your passphrase but you _cannot type in the box_

OSX: 10.8.5

**Comment by deanc** [comment]
I can still confirm that this issue persists, and it is definitely related to coming out of sleep. It happens consistently. 

Open lid, load sequel pro, make ssh connection. Close lid. Open lid. Try and do something in the window (ssh connection has of course dropped), pops up password prompt but cannot interact with it and have to force quit.

**Comment by dmoagx** [comment]
> Open lid, load sequel pro, make ssh connection. Close lid. Open lid. Try and do something in the window (ssh connection has of course dropped),

I do that a lot and never have had any problems.
The issue is most likely related to some models of routers or some ISPs.

When Sequel Pro asks for the password which you can't enter, is the UI still responsive (e.g. the close button in the upper left corner animates when you hover over it) or is it beachballed?

Please go to Console.app and search for any events from Sequel Pro from around the time of the crash.

While Sequel Pro hangs, go to Activity Monitor, select Sequel Pro and go to View > "Analyze Process" (or maybe "Sample Process") and post that output here.

**Comment by deanc** [comment]
Hi,

This is definitely not related to routers, or ISPs. I've been travelling all over Europe this summer in three different countries, and probably used about 50 different wifi networks. It happens consistently everywhere when I wake my laptop, as well as at home and office.

When sequel pro asks for the password, the UI is completely unresponsive. The close button is not even red. The other buttons are there but no hover state. I cannot get any kind of interaction out of the UI. After I switch focus I can no longer bring the frozen window to the front. I always have to force-quit.

Can you provide instructions for Console.app? I don't understand? Where would I look for the events?

Also there is no Analyze process in Activity Monitor. There are others. Which one do you want me to do?

**Comment by dmoagx** [comment]
> Can you provide instructions for Console.app? I don't understand? Where would I look for the events?

Open Console from /Applications/Utilities/Console.app
Make sure "All messages" is selected on the left and type "Sequel Pro" in the search field in the upper right corner. Post all messages that are displayed.

> Also there is no Analyze process in Activity Monitor. 

It might be named "Sample Process" on your system.

**Comment by deanc** [comment]
Console.app as you said:
http://pastebin.com/7mwizN11

Sample process:
http://pastebin.com/2p4eQAqG

**Comment by dmoagx** [comment]
1.0.2 is too old to be helpful for debugging anymore.
Please try a nightly build or at least 1.1rc1: http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/

**Comment by dmoagx** [comment]
Looked a bit further into it:
As per the sample Sequel Pro is actually alive and waiting for the password input. 

SPMySQLs `_reconnectAllowingRetries:` is designed to block while allowing the UI to continue:
```objc
		while (reconnectingThread) {
			//...

			[[NSRunLoop currentRunLoop] runMode:NSModalPanelRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:0.1]];
			//...
		}
```
However a quick test suggests that run loop mode might not be enough to actually allow UI input.

**Comment by dmoagx** [comment]
I made a special debug build with additional logging: http://dev.sequelpro.com/uploads/sequel-pro-i2526.dmg

Please open Console.app and search for Sequel Pro, then start the debug build and post the output from console once the hang occurs.

**Comment by keithmichelson** [comment]
I have the same issue, after going to sleep when password prompt appears everything freezes.

**Comment by dmoagx** [comment]
Well, then you should try what I've asked for in the comment above yours...

**Comment by e-gaulue** [comment]
Hi dmoagx,

Don't know if it will help, but I used the above mentioned version and here is what I get:
`18/12/2016 15:13:16,950 Sequel Pro[32266]: Failed to connect (exportCustomFilenameTokensField) outlet from (SPExportController) to (NSTokenField): missing setter or instance variable
18/12/2016 15:15:44,089 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:647 lock answerAvailableLock...
18/12/2016 15:15:44,089 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:651 performSelectorOnMainThread...
18/12/2016 15:15:44,089 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel workerGetPasswordForQuery:]:675 enter
18/12/2016 15:15:44,090 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel workerGetPasswordForQuery:]:699 beginSheet:...
18/12/2016 15:15:44,546 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel workerGetPasswordForQuery:]:702 leave
18/12/2016 15:15:44,546 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:654 waiting for return of answerAvailableLock...
18/12/2016 15:15:49,461 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel closeSSHPasswordSheet:]:710 enter
18/12/2016 15:15:49,748 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel closeSSHPasswordSheet:]:737 unlock answerAvailableLock...
18/12/2016 15:15:49,762 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:665 unlock answerAvailableLock.
18/12/2016 16:29:52,547 WindowServer[181]: CGError post_notification(const CGSNotificationType, void *const, const size_t, const bool, const CGSRealTimeDelta, const int, const CGSConnectionID *const, const pid_t): Timed out 1.000 second wait for reply from "Sequel Pro" for synchronous notification type 102 (kCGSDisplayWillSleep) (CID 0x8f4a7, PID 32266)
18/12/2016 17:55:02,117 Sequel Pro[32266]: This application is trying to draw a very large combo box, 1314 points tall.  Vertically resizable combo boxes are not supported, but it happens that 10.4 and previous drew something that looked kind of sort of okay.  The art in 10.5 does not break up in a way that supports that drawing.  This application should be revised to stop using large combo boxes.  This warning will appear once per app launch.
18/12/2016 22:57:10,285 Sequel Pro[32266]: CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
18/12/2016 23:44:16,117 Sequel Pro[32266]: CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
19/12/2016 09:55:48,742 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:663 enter
19/12/2016 09:55:48,742 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:703 I am the reconnectingThread now.
19/12/2016 09:55:48,742 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:718 _disconnect
19/12/2016 09:55:48,742 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:722 _lockConnection
19/12/2016 09:55:48,742 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:726 _waitForNetworkConnectionWithTimeout:
19/12/2016 09:55:48,793 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:739 proxy == YES
19/12/2016 09:55:48,793 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:762 proxy connect
19/12/2016 09:55:48,793 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:766 waiting for SPMySQLProxyConnected
19/12/2016 09:55:50,001 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:647 lock answerAvailableLock...
19/12/2016 09:55:50,048 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:651 performSelectorOnMainThread...
19/12/2016 09:55:50,299 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel workerGetPasswordForQuery:]:675 enter
19/12/2016 09:55:50,305 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel workerGetPasswordForQuery:]:699 beginSheet:...
19/12/2016 09:55:50,786 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPSSHTunnel workerGetPasswordForQuery:]:702 leave
19/12/2016 09:55:50,787 Sequel Pro[32266]: <NSThread: 0x10760a030>{number = 3, name = (null)} -[SPSSHTunnel getPasswordForQuery:verificationHash:]:654 waiting for return of answerAvailableLock...
19/12/2016 09:56:14,235 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:796 warning! this is the 100th time timeout has been extended because of SPMySQLProxyWaitingForAuth
19/12/2016 09:56:39,315 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:796 warning! this is the 200th time timeout has been extended because of SPMySQLProxyWaitingForAuth
19/12/2016 09:57:04,408 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:796 warning! this is the 300th time timeout has been extended because of SPMySQLProxyWaitingForAuth
19/12/2016 09:57:29,487 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:796 warning! this is the 400th time timeout has been extended because of SPMySQLProxyWaitingForAuth
19/12/2016 09:57:54,580 Sequel Pro[32266]: <NSThread: 0x100912840>{number = 1, name = main} -[SPMySQLConnection(PrivateAPI) _reconnectAllowingRetries:]:796 warning! this is the 500th time timeout has been extended because of SPMySQLProxyWaitingForAuth
`

Ready to test more if needed.

**Comment by dmoagx** [comment]
@e-gaulue Thanks, that mostly confirms what I was already suspecting. See my comment in https://github.com/sequelpro/sequelpro/issues/2503#issuecomment-260461822

**Comment by dmoagx** [comment]
Merging with #2503 
Those are the same issues but the other ticket is clearer about the underlying problem.
