### ISSUE TITLE
Stalls on connect

### ISSUE THREAD

**Issue by billynoah** [sequelpro/sequelpro#1959]
For some sites I am able to connect successfully but then get a spinning beachball and the application stalls for approx 1 - 2 minutes before finally resuming normal operation.  It doesn't crash, just an extended stall followed by a successful connection.

This only seems to happen with "Standard" connections, never with ssh, and only for some databases.  My settings for the connections that stall are default (port 3306, no db specified).

I am using v1.0.2 and OS X 10.8.5

**Comment by dmoagx** [comment]
I think this issue is too old now, to be able to analyze it, so I'll close it.

However `skip_name_resolve=off` indicates that the server will try to do DNS reverse lookup for every connecting IP and if DNS servers are not properly configured somewhere in the chain this can cause MySQL to stall until a timeout is reached, which is what I originally suspected.
