### ISSUE TITLE
Save As... for SQL Queries

### ISSUE THREAD

**Issue by donblaylock** [sequelpro/sequelpro#1997]
If you have multiple tabs open with different queries in each tab it gets confusing sometimes.  For example, I saved query in Tab1, at some point later in the day I saved the query in Tab2 but I saved it as the same name (accidentally) and overwrote my query from Tab1.  
PLEASE!  The application should keep track of the query filename that you have open in each tab separately then saving that query will not wipe out previous work.  When you save a query it currently defaults to that last saved filename regardless of which table you are in.  Opening a saved query should retain the filename for that tab and when you save that query, default to the filename that was opened - in that tab.  This is pretty standard behavior.  You can look at how SQL Server handles this for the correct behavior.  I lost several hours of work today because of this issue. FYI :o)  BTW, I LOVE THE APP!

**Comment by gjreda** [comment]
+1

Sequel Pro _used_ to present the "Save As" dialog every time the user selected "Save Query". This seems to have been removed in the most recent release.

Now, if you open a previously saved query in a new tab, then make drastic changes to that query, Sequel Pro will immediately overwrite the previous version. The old version used to notice that you've made changes and at least take you through the "Save As" dialog window - not implicitly overwrite.

**Comment by thomasruns** [comment]
Apparently the feature is still there (SHIFT + CMD + CTRL + S), but the behavior of the menu item was changed, which doesn't make any sense to me. +1 on adding this back and a simple display of which query file is opened in a tab.

Doing so doesn't make Sequel Pro a text editor, it makes it a DB tool with standard features that all other DB tools have. A huge part of working with databases is writing and editing queries. If Sequel Pro becomes a tool that treats files as things that should be imported, and never edited/saved.. I have a feeling a lot of users will be finding a new tool. I sure hope that's not what ends up happening, because I love using Sequel Pro.

**Comment by eboyle-invoca** [comment]
I generally like Sequel Pro but to say that the you are okay with overwriting people's work by simply saying 'we are not an editor' is just a cop-out.
Either fix the Saving of the files to match the files in the Tabs or just remove the idea of having Tabs altogether.
Oh, and removing the "Save As" option from the menu - that was just plain evil.

**Comment by vhdes** [comment]
+1 add a "Save As..." menu item or restore the previous Save behavior that respects the fact that the buffer/editor contents have changed since the last open.  The ludicrous alternative is to copy and rename the file to what you want it to after it is edited but before you actually open it (apparently that makes sense to someone).
