### ISSUE TITLE
SSH Port Forwarding uses non-standard syntax

### ISSUE THREAD

**Issue by ryansch** [sequelpro/sequelpro#2050]
The correct syntax for local port forwarding is `-L [bind_address:]port:host:hostport` but sequel pro uses forward slashes instead of colons between fields.  This works for some reason with apple's supplied ssh but doesn't work if you build a newer ssh from brew.  Apple's ssh works with the standard syntax.

**Comment by ryansch** [comment]
I currently have Apple's ssh and brew's ssh installed and I can confirm that they're both happy if I use colons in the command string that sequel pro tries to use.

**Comment by dmoagx** [comment]
Indeed, the source code from opensource.apple.com and openssh.org confirms this.

I'm taking a wild guess and say this addition was made because in early versions of OS X (and before) `:` was the path separator, so OS X had the habit of swapping `/` and `:`.

Sequel Pro has always used the `/` syntax back to CocoaMySQL: https://github.com/sequelpro/sequelpro/blob/0f586da34dac2c764a12055158e4929cf69340a1/SSHTunnel.m#L429-L434 (which was based on STM http://projects.tynsoe.org/en/stm/ )

As for changing it:
Sequel Pro actually **requires** Apples SSH, by which I mean we do not support any other ssh implementations and we don't want to deal with the issues that might be caused by slight differences between them. That might sound harsh, but even supporting only Apples SSH across a few versions of OS X turned out to be quite the hassle.

I'll leave this open for the other project members to add their opinion.

**Comment by ryansch** [comment]
For what it's worth, I have the ssh command that sequel pro tries to use working just fine with OpenSSH_6.7p1 after replacing the `/` with `:`.  I'm just manually establishing the tunnel right now.

**Comment by ryansch** [comment]
At the very least, could this be configurable?

**Comment by dmoagx** [comment]
OK, I looked at the actual change in OpenSSH and they had supported the / syntax until recently.
However in CVS 1220 (OpenSSL version 6.7?) they added support for forwarding UNIX domain sockets.

As those are paths there would be an ambiguity with the `port/host/port` syntax so it's obvious why they removed it.

Assuming Apple will also adopt this change at some point (probably 10.11 or so :see_no_evil: ) I'll merge the proposed commit, hoping it won't break anything...

**Comment by ryansch** [comment]
Excellent!  I'll close in favor of #2053.

**Comment by paranic** [comment]
great job ppl
well done!

**Comment by deanhowe** [comment]
Yeah, hat's off. Looks like the release cycle of new OS X versions and a Public Beta program are paying off. Hit the SSH problem today after updating to 10.11 - updated SequelPro and now everything seems fine. Well done, and thank you!

**Comment by bibyzhang** [comment]
I suffered this problem as well,but now all is well,thanks!

**Comment by webtoolbox** [comment]
I am still getting this error. I have the newest version of sequel pro (1.1) and OSX. OpenSSH version is 6.9. The sequel pro error says "MySQL said: Can't connect to MySQL server on '127.0.0.1' (4)".

This was working fine until I upgraded OSX to El Capitan. Any suggestions?

**Comment by dglangley** [comment]
Just adding my voice to say 'thank you' to your diligence on this issue, I also suffered from the same problem and have equally benefitted from the above solution! Thank you!

**Comment by PeterStub** [comment]
If using Sequel Pro / El Capitan - just get the latest Sequel Pro here:
http://nightly.sequelpro.com/

**Comment by dmoagx** [comment]
@PeterStub  This has long been fixed in the official release version.

**Comment by hearlapati-phunware** [comment]
I've had similar error, Upgrading to Latest SQLPro(1.1.2) solved the problem.
