### ISSUE TITLE
[REQ] Command Line access with connection options

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#206]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=206
Reporter:arie...@gmail.com Date:2009-03-26 01:04:56 Status:Accepted

I'd be great if there was some kind of shell command available so it's possible to open Sequel Pro 
from the console and open a connection directly. E.g.:

   sequelpro root@localhost

or 

  sequelpro --database my_app --user username --password secret --host remote_host

This would especially work great with my current mysql-over-ssh-tunneling script. If this is 
already possible, I couldn't find it anywhere.

**Comment by klein0r** [comment]
Is there a solution in the latest version?

**Comment by stuporglue** [comment]
I'd like to be able to open a connection from the command line too. Generating a temporary .spf file looks like it'll work, but just feels hacky. 

Something modeled on mysql's CLI parameters would be ideal (`sequelpro --database my_app --user username --password secret --host remote_host`). 

Since there's already the URL Scheme support though, perhaps it could be extended to accommodate connections (`sequelpro://ConnectToServer/user:password/host/database`) or something. 

Thanks for the great software!
-- Michael

**Comment by dmoagx** [comment]
There will be support for MySQL URLs in the next release. See #1681

**Comment by MACscr** [comment]
Ugh, no ssh support though and thats 100% of my connections.

**Comment by weitzman** [comment]
I second that request. ssh connections would be helpful.

fwiw, .spf files are not working for me.

**Comment by krishaamer** [comment]
+1 need this

**Comment by artdevgame** [comment]
I'm using vault to generate dynamic username/passwords for different connections. This feature request would be useful in that situation.
