### ISSUE TITLE
Run Current vs Run previous at the End of a line

### ISSUE THREAD

**Issue by haxplorer** [sequelpro/sequelpro#2061]
When the cursor is at the end of a line where the SQL ends, Sequel Pro currently makes the button "Run Previous". But as a user I still think that I'm on that query which just ended at my cursor. So, it is a bit confusing, and makes me think for a few seconds. Instead of changing the button from "Run Current" to "Run Previous on reaching the line end, please change it only when the cursor moves to the next line, unless you see that another query is starting in the same line after the semicolon.

**Comment by rowanbeentje** [comment]
Heh.  The behaviour here was added because users had very different views on what "Run Current" meant when the cursor was after a semicolon.  I think perhaps what you suggest about not changing the button if there's no further query at all in the text box makes sense, but I don't think we'll be differentiating by linebreaks - to those who use linebreaks liberally within queries anyway, semicolons matter much more.

I think using the text "Run Previous" is a reasonable compromise for still performing the action that *most* users expect, but trying to indicate so clearly.

**Comment by dmoagx** [comment]
I highly recommend to go to Prefs > Editor and enable "Highlight current query".
That makes it pretty obvious which query will be run.

**Comment by ye** [comment]
Just to chime in here that `command-r` is considered Run Next instead of Run Current when the cursor is inside the comment at a line ending with that comment. See below.
![screen shot 2016-04-28 at 3 32 34 pm](https://cloud.githubusercontent.com/assets/133924/14900247/ab72542c-0d5d-11e6-9a7c-e2589bd665e7.png)
Not sure if that's a desired behavior.

**Comment by abhibeckert** [comment]
@ye I have noticed this as well and agree it's not ideal.

Right now we split queries on the semicolon character, but it would be better to split on the newline after a semicolon (unless there is actually a query after the semicolon).
