### ISSUE TITLE
[REQ] SSL SHA256 Connection

### ISSUE THREAD

**Issue by EminezArtus** [sequelpro/sequelpro#2071]
Currently I am not able to connect with SHA256 Certificates only with SHA1 and SHA2

> MySQL said: SSL connection error: ASN: bad other signature confirmation

**Comment by dmoagx** [comment]
SHA-2 is SHA-256 (and some others).
Also this works fine for me:
```
$ openssl x509 -noout -text -in client256-cert.pem 
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 3 (0x3)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=... snip ...
        Validity
            Not Before: Feb 23 22:34:59 2015 GMT
            Not After : Jan  1 22:34:59 2025 GMT
        Subject: C=... snip ...
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:b2:bf:b2:59:2f:da:86:7e:ea:8a:03:52:2f:f1:
                    aa:cf:90:... snip ...
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
        10:e4:8f:e9:0b:c4:59:49:bf:00:c3:6e:4c:d5:f6:a2:1e:43:
        85:52:dc:fd:5a:aa:... snip ...
```
Some observations though:
* The error displayed by the client might not be the real error. With Wireshark I saw the server fall back to plaintext after a failed handshake, which the client on the other hand could not interpret.
* Make sure certificate and key are configured in the right order in Sequel Pro
* If you `REQUIRE X509` a user the ca file/path *must* be set and valid.
* Make sure the client certificate is valid (esp. in regard to the servers local time!)

Sequel Pro 1.0.2
MySQL 5.5.41-0ubuntu0.14.04.1-log

**Comment by dmoagx** [comment]
Disregard the previous comment, you could have saved me a lot of time if you had actually mentioned that you are talking about **the server's certificate!**

Yes, Sequel Pro's mysql client currently is 5.5.33 which uses a yaSSL version that can't yet handle SHA256/284/512.
We need to update to a more recent release for that.

**Comment by EminezArtus** [comment]
Yes sir you can't connect to a server with sha256 I can connect just fine with phpstorm but not with sequel. :D im 100% sure my cert is good.

**Comment by dmoagx** [comment]
I looked into updating the MySQL library, but the current **5.5.42** version fails to build with SPMySQL unless I link against `libstdc++`.

I stepped through the versions and this issue was introduced in **5.5.40** in `extra/yassl/taocrypt/include/runtime.hpp` where they made `__cxa_pure_virtual` `static`. clang seems to interpret the static keyword a bit different and hides the function so it turns up undefined in the other files?
Unfortunately, 40 is also the version where they added support for SHA256.

Since just removing the static keyword seems to be enough to make it work again with Sequel Pro, I'll just go ahead and commit it. **I'd very much appreciate a second opinion on this issue, though**.
Additionally, 42 disables SSL2/3 support, so let's see how many people will scream.
