### ISSUE TITLE
compiler warnings: instance method 'xxxxx' not found

### ISSUE THREAD

**Issue by tessus** [sequelpro/sequelpro#2089]
When I compile SequelPro, I get around 40 warnings. Most of them are semantic issues where the instance method is not found.

`warning: instance method 'xxxxxx' not found`

There are also a lot of deprecation warnings in `Sequel Pro QLGenerator` and `PSMTabBar`.

The entire log file for one compilation run is 2332 lines long, thus I won't post it in this ticket. It's available [here](https://evermeet.cx/p/logs/warnings.txt).

I know that warnings are not errors, but they can indicate a problem that might have been ignored too long. I'm not quite sure, why those are warnings and not errors. If somebody used a method which wasn't there, the consequence would be a crash. But since I haven't seen SequelPro crash, I assume the methods are there, but the compiler does not see them.

You somebody shed a light on this?

**Comment by dmoagx** [comment]
Half of the warnings in that file are from `genstrings` and have no impact at all.

The `windowUUID` and `orderedDocuments` warnings come from a scoping violation/missing `#imports`. As you already noted, the methods are actually present at runtime. Solving that issue is more of a design rather than technical question.

The deprecation warnings should indeed be fixed at some point, but I don't remember Apple ever having removed a deprecated method from OS X, so this is a pretty low priority.

**Comment by tessus** [comment]
Ok, I just wanted to make sure that you are aware of the warnings and wanted to get my mind at ease by asking for clarification. Thanks for the info. Closing.
