### ISSUE TITLE
Fast scroll to column in content view

### ISSUE THREAD

**Issue by darkogoles1** [sequelpro/sequelpro#2174]
Hi, I am using Sequel pro a lot and have an idea that could help save some time and make UI more useful. 

When working with tables / with many columns, it is problematic to find if some column exists in specific table and to scroll to it quickly to see it's records.
I would like if possible to have some search field to do quick search for column in table content and scroll to that column. Currently manual scrolling in table with about 200 columns is not easy and finding specific column is hard and time consuming.

![2015-07-14_10-38-35](https://cloud.githubusercontent.com/assets/5793864/8676570/b766b7d8-2a4a-11e5-9105-743f5beaeffb.png)

Thanks in forward

**Comment by gileswells** [comment]
@darkogoles1 I gotta say I love this idea from a concept of being able to search for a column. I'm not a developer on the project but me personally I hate putting a special case on a field that is clearly in use for something entirely different. 

What I would LOVE to see pulls some from Sublime Text and other apps that have fuzzy searching. If there was a hotkey that brought up a box, maybe spotlight style in front of everything, that worked as a fuzzy search and then as you typed in letters the table behind it started losing columns that didn't match the fuzzy search until you got down to the table column you wanted or selected the one you wanted from the remaining list in the spotlight fuzzy search. Once all is said and done, since we may need neighboring columns and whatnot have everything come back and scroll you horizontally to that column.

Mind you I have 0 desktop app development experience or I would love to jump in and lend a hand but I love the app you guys have and continue to put put. Just trying to pop a comment on this feature request because I can see its use case very much I just disagreed with the proposed implementation above and thought I had an improved flow that could also do the trick.

**Comment by jimlongo56** [comment]
Similar to https://github.com/sequelpro/sequelpro/issues/1709, would be most welcome.

**Comment by koppelaar** [comment]
+1

**Comment by adfink** [comment]
This would be such a nice feature.  Any chance of it coming soon?
