### ISSUE TITLE
Advanced filter content widow is broken in OSX 10.10.2

### ISSUE THREAD

**Issue by lumpynifkin** [sequelpro/sequelpro#2201]
Try to use the advanced filter content in OSX 10.10.2, it does not work in sequel pro 1.0.2 or 1.1

The window loads with no rows showing, even though I can click where a row would be and the row gets highlighted.  I also can't type into the where query box.

**Comment by dmoagx** [comment]
Works for me on 10.10.4 with 1.1rc1 and nightly builds.

The WHERE box is a preview of the query. It is read-only by design.
Also the table is empty by default, because you are supposed to input the filter criteria there.
![bildschirmfoto 2015-08-11 um 21 52 47 738](https://cloud.githubusercontent.com/assets/5793864/9208354/5c4b4154-4073-11e5-9514-1a47dcd15f6a.png)

**Comment by lumpynifkin** [comment]
Sorry, misunderstood how it works, thanks for the quick demo
