### ISSUE TITLE
backup of com.sequelpro.SequelPro.plist

### ISSUE THREAD

**Issue by studious** [sequelpro/sequelpro#2212]
I am using Mackup to keep my computers in sync but when I start SequelPro on my original machine it loads a copy of com.sequelpro.SequelPro.plist.aslkdfj (for instance) from somewhere and then writes over my symbolic link ~/Library/Preferences/com.sequelpro.SequelPro.plist when it renames the temp file.

This behaviour doesn't occur on my second machine. Is there anything I can do to keep the symbolically linked ~/Library/Preferences/com.sequelpro.SequelPro.plist ?

**Comment by rowanbeentje** [comment]
Hi @studious, Sequel Pro doesn't do anything special with the .plist files - they're managed by the system's standard NSUserDefaults libraries.

Are your machines on the same OS version?  As of Mavericks, OS X started caching .plist files so that quitting the program and replacing the file is no longer sufficient to actually load the new file (instead the old values will keep being used and will overwrite the new file!).  Could that be causing what you're seeing?  See http://hints.macworld.com/article.php?story=20130908042828630 for some methods of working around this.

**Comment by studious** [comment]
Thanks, I wasn't sure if it was SequelPro or OS X. I am using Yosemite on both machines. I'll look into it further when I have time.

**Comment by dmoagx** [comment]
Closing as this is no issue with Sequel Pro.
