### ISSUE TITLE
Scroll sticking

### ISSUE THREAD

**Issue by nexbridge** [sequelpro/sequelpro#2216]
The scroll sometimes seems to stop the moment your fingers leave the touchpad, rather than continuing for a little while and gracefully coming to a halt like normal.  The issue is most obvious with sideways scroll when you run a query like SHOW SLAVE STATUS and then try to scroll back and forth across the result columns.

FYI, I'm using Sequel Pro 1.1 RC2, and OS X 10.10.5.

**Comment by dmoagx** [comment]
Sequel Pro just uses the standard table view and scroll view controls like every other OS X app.

What I did notice however, is that OS X tries to detect the direction of your swipe and will lock the scroll axis if it succeeds. However, if you use your right hand to swipe from left to right (with your palm at the lower right corner of the touchpad) you are likely to do a diagonal movement which will not be detected as a horizontal swipe.
OS X will then thwart the scroll as soon as it reaches an edge of the table which in that case would be the upper edge.

Try monitoring your hand movement. Perhaps swiping with your left hand (with the palm to left of the trackpad) works better.

**Comment by nexbridge** [comment]
Thanks for getting back to me.  I tried doing what you suggested by using deliberately horizontal swipes with a negligible vertical element, but I'm afraid the issue persisted.  Are you able to replicate the issue as I described it using SHOW SLAVE STATUS on OS X 10.10.5 and repeatedly trying to scroll left and right?  Basically the only solution seems to be to keep your fingers on the trackpad, but you swiftly run out of trackpad doing that, so you really just want to "flick" it so that it "keeps going" for a little while after your fingers have left the trackpad, which I thought was the usual behaviour in OS X 10.10.5, so I'm surprised you're saying it's using the standard controls - although thinking about it, the resolution on my monitor is quite low, in that a SHOW SLAVE STATUS query with an empty result only shows ten-or-so columns on the screen, which means there's a lot of scrolling required to get to the right-hand end, which is probably exacerbating the issue, or at least making it easier to replicate!  I'd just upgraded from OS X 10.7.5, and I don't remember having the issue previously, so perhaps it's a change in the OS X behaviour, but if you're able to fix it in your application it would be appreciated!

**Comment by gileswells** [comment]
I too can replicate the issue and noticed it right after the update to version 1.1. Hoping there is some sort of fix that can be done for this. It wasn't happening in the previous version.

**Comment by dmoagx** [comment]
Yes, there is a notable difference between 1.0.2 and 1.1.
However in Xcode both versions are visually exactly the same.

Here is the related XML: https://gist.github.com/dmoagx/d605b092c5079d11529f

**Comment by drew-gross** [comment]
I also have this issue. I went back to 1.0.2 and the problem disappeared.

**Comment by abhibeckert** [comment]
@drew-gross we would have liked to wait a bit longer before shipping 1.1 but we had to get it out because of El Capitan issues (especially SSH tunnelling). Hopefully we can fix minor issues like this soon and do a 1.1.1 release.

**Comment by finger-berlin** [comment]
After the latest update to 1.1 on 10.10.5 again I can't scroll wide (many cols) result sets.

I am sure we had this issues back a couple of months (or even years?) ago. Last time it was somehow related to an upcoming OSX release. ;-)

This problem is not really a "minor" issue. I have a lot of times large tables where I scroll many times back and forth between the first and the last column. Especially when you have just one row as a result, the bug is really annoying because I can't see the benefit in being able to scroll a one line result vertically. ;-)

However, many thanks for the outstanding work so far!!!

**Comment by yannickmcosta** [comment]
I have also started experiencing this issue, even on 1.1. Try and scroll to the side and get a slapback effect from the scroll. Upgrading to El Capitan later so will see if issue is prevalent there too.

**Comment by pdesmarais** [comment]
Same issue here. But that is even more accentuated by the fact that when you refresh a list (table Content view with filter specified and do Cmd-R), the scroll position now gets set back to the leftmost position of the list. So if I happen to be viewing a table with let's say 50 columns and I'm at the righmost position possible, I get sent to the leftmost position of the list and need to scroll to the right again. Previous version kept the scroll position exactly where it was.

**Comment by dmoagx** [comment]
@pdesmarais Open a new issue about the scrolling position. This one is specifically about the "rubberband snapping" effect.

**Comment by bobtista** [comment]
Same issue here, right after the update to 1.1

**Comment by dmoagx** [comment]
The commit which introduced this issue was 7ae31e80623186465fa94e8e517fe0d56b32477f

**Comment by rowanbeentje** [comment]
Hmm.  I also moved the tableview one level deeper in nesting, putting it inside a splitview... maybe there's now multiple scrollbars conflicting?

**Comment by dmoagx** [comment]
This it how the hierarchy looks like for Xcode:
![bildschirmfoto 2015-10-06 um 14 03 26 637](https://cloud.githubusercontent.com/assets/5793864/10308129/033ce116-6c34-11e5-9337-43920e88af46.png)
It looks like there is only one scroll view involved.

**Comment by dmoagx** [comment]
So I tried to move the table view up one layer and that indeed seems to fix the sticking.

**Comment by gileswells** [comment]
@dmoagx do you have a build or a commit I can reference to try and see if the issue is resolved on my system as well?

**Comment by dylanwenzlau** [comment]
This is a huge issue for me as well, after upgrading to 1.1. I don't know how the native Mac OS scroll logic works, all I know is that the scroll worked great before I upgraded, and it works great on all other Mac applications I use, but now it's completely broken and painful to use in Sequel Pro. Please, please, please push a fix for this as soon as possible.

**Comment by hostep** [comment]
We also experience this problem after upgrading to 1.1 and it is really, really annoying. Would be great if somebody got some time to try to fix this :)

**Comment by arlomedia** [comment]
I just installed Sequel Pro 1.1.1 and can no longer reproduce the problem with horizontal scrolling, but it still happens about 1 in 4 times when scrolling vertically in a large table. It might be that only an especially fast scroll gesture triggers it, but I'm not sure. If that's the case, it might also happen with horizontal scrolling if I had a table with enough columns.

**Comment by gileswells** [comment]
This is fixed for me in 99% of cases. The only time it persists is when I am at the top of the content page and pull down too much while flinging sideways. Most of the time it doesn't catch even when its not a perfectly horizontal scroll. 

:+1: thanks for the hard work guys!

**Comment by dmoagx** [comment]
We didn't change anything…

**Comment by arlomedia** [comment]
I interpreted your second comment on October 6 to mean that you made a change for version 1.1.1. I just installed that version this morning and it seemed better after some initial testing. But indeed, after further use, I am now seeing the "stuck scrolling" with both horizontal and vertical scrolling, with no apparent pattern.

**Comment by raffecat** [comment]
I am seeing this issue still, in version 1.1.2 on Mac OS 10.10.5.

It's a major issue for me because I work with a lot of large tables that contain many columns and rows. Doing anything is slow and frustrating.

- To scroll (horizontally or vertically) to the end of a table takes many many individual swipes
- Momentum scrolling does not work at all - it rubber bands on the very next row or column after lifting fingers off the pad.
- Using the scroll bar instead requires first swiping, then very quickly moving the mouse over the scroll thumb that appears (it's not a viable work-around)

This is caused by the way scrolling works internally in OS X: the view you are scrolling can send an "end of content" message back to the OS when processing a scroll event, to tell the OS that it has reached the end of the content, and the OS then applies the rubber-band snap back effect.

This can cause problems if you are:

- dynamically adding content to the table as the user is scrolling
- some parent or child of the table view accepts scroll events (and sends the "end of content" message)
- you are programmatically setting the scroll position in reaction to scrolling events (e.g. implementing your own smooth scrolling on top of the OS scrolling)
- maybe changing some property during scrolling that causes the view to resize
