### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by theskillwithin** [sequelpro/sequelpro#2241]
It would be great to have added support for accessing vagrant / puphpet vagrant / vm's 

automatically locating the ssh key or password for example

**Comment by bajax** [comment]
I'd like to see scriptable configuration myself, such that someone could write a plug-in for Vagrant to do this.  Is there such a thing as a URL scheme for database servers?  That may be an even better option.

**Comment by Spriz** [comment]
I'm not sure I see the needs for this... why not just locate the ssh key with the finder?

**Comment by linkingarts** [comment]
re the ssh key, that is all you need to do, locate the key which is usually in `.vagrant/machines/default/virtualbox/private_key` (which may make the case for adding that as a default?)

**Comment by iamkobold** [comment]
I would also add there is sometimes and issue with the SSH known_hosts with multiple vagrant VMs and a local VirtualBox installation. Such that depending on the order in which VM's are booted there is some auto-negotiating of ports such that there are times when SequalPro rightfully complains about the SSH host key changing when it happens to be running on a different port. So if SequalPro could be more aware of Vagrant things like this. Including the default key as stated above. It would be a nice addition to the tool.

**Comment by Spriz** [comment]
@iamkobold sounds like you have multiple machines with the same ids/host names/ips or something alike :-)

**Comment by iamkobold** [comment]
Well in SequalPro they are all SSH connections to localhost to usually something like 2200 or 2222 or whatever other trickery vagrant does with virtual box for port forwarding conflict/negotiation. There is something i think vagrant does with the SSH connection that allows the SSH host/port to vary but knows it's still the right machine. The workaround is to blow away the known_hosts entry for localhost or 127.0.0.1 every now and again.

**Comment by willpower232** [comment]
> The workaround is to blow away the known_hosts entry for localhost or 127.0.0.1 every now and again. 

Having done this being a vagrant'er myself, I wouldn't be surprised if this is the only option as the issue is with having multiple VMs on the same hostname "localhost:2222".

If you want to run different connections (or frequently have multiple machines running simultaneously), theres nothing stopping you changing the port from 2222 to anything else to avoid the collision on both your computers networking arrangement and the known_hosts file:
[https://realguess.net/2015/10/06/overriding-the-default-forwarded-ssh-port-in-vagrant/](https://realguess.net/2015/10/06/overriding-the-default-forwarded-ssh-port-in-vagrant/)
