### ISSUE TITLE
SSH ControlPath stops working from version 1.1

### ISSUE THREAD

**Issue by chernjie** [sequelpro/sequelpro#2271]
It appears that 3a89efa has caused SequelPro to stop working for me. It apparently fixed a bug which I depended on to get connection to a DB behind a jump host.

Via https://github.com/sequelpro/sequelpro/issues/1457#issuecomment-28119545, I found the secret flag `SSHMultiplexingEnabled`
```bash
$ defaults write com.sequelpro.SequelPro SSHMultiplexingEnabled -boolean YES
```

Unfortunately it did not work for me as it hijacks the `ControlPath` to not use existing connections.

Would it be possible for SequelPro to let SSH behave as the user intended instead of all these sophisticated work around?

**Comment by chernjie** [comment]
For example: 4f108ad

**Comment by dmoagx** [comment]
The SSH support in Sequel Pro is meant to cover the most generic use cases.
We added the connection multiplexing option to reduce the number of "heavyweight" ssh connections when connecting to the same server multiple times. It turned out to work pretty bad for the majority of users, so we had to disable it. 

If you find that Sequel Pros SSH support does not fit your very specific setup there are two options:
a) Don't use it. Just create a regular connection and manually invoke ssh with the `-L` option before connecting.
b) Configure a script as SSH binary in Prefs which can override command line options as needed.

**Comment by chernjie** [comment]
@dmoagx Thank you for your kind thoughts.

Since `SSHMultiplexingEnabled` is a secret flag that is only meant for heavyweight users, turning on the flag should not need to additional `ControlPath` configurations.

**Comment by chernjie** [comment]
@dmoagx please see #2272 for the submitted patch

**Comment by abhibeckert** [comment]
We disabled muxing because it caused problems for too many users, and don’t want to enable it again.

Please use the workaround suggested above.

**Comment by chernjie** [comment]
I have created a custom SSH script to ignore the ControlMaster setup and it seems to be working fine so far. https://gist.github.com/chernjie/63df9a1c6f8e74d01849

**Comment by abhibeckert** [comment]
Thanks @chernjie
