### ISSUE TITLE
Shortcut Recorder needs update

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2300]
Shortcut Recorder is currently causing this console message:

```
*** WARNING: -[NSImage dissolveToPoint:fraction:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
```

**Comment by dmoagx** [comment]
Oh, well, so there is now:
* The original and pretty much abandoned project: https://github.com/shortcutrecorder/shortcutrecorder 
* And two forks: https://github.com/shpakovski/MASShortcut
* https://github.com/Kentzo/ShortcutRecorder

which are both accusing the other of being 'bad': https://github.com/Kentzo/ShortcutRecorder/pull/27#issuecomment-70493100

**Comment by stuconnolly** [comment]
The above warning was fixed in https://github.com/shortcutrecorder/shortcutrecorder/commit/c89b122dc2c688234ce9e8ebe264485374c46306 in https://github.com/shortcutrecorder/shortcutrecorder

Looks like Rowan was the only person to ever update it https://github.com/sequelpro/sequelpro/commits/master/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder which included some memory issues.

Will check with him with regard to the source he was using, but the changes necessary to support dark mode are pretty straightforward.
