### ISSUE TITLE
Encoding/Collation option disabled, but still choosable.

### ISSUE THREAD

**Issue by TheDigitalOrchard** [sequelpro/sequelpro#2316]
It seems that when a table is set to UTF-8, but a field is set to something else (ie. Latin1), when choosing the encoding for the fields, the table's encoding is shown as greyed-out. This would normally suggest that it can't be selected, yet it does seem to be selectable. This is confusing and not compliant with the Mac UI. Can you provide an explanation and maybe figure out a better way to show the table's encoding?

![sequel-pro-option](https://cloud.githubusercontent.com/assets/3195423/10924301/a75f0564-823a-11e5-88ba-543358535b3b.png)

**Comment by dmoagx** [comment]
It is greyed out because it matches the table encoding.
If you look at the CREATE TABLE statement you will see that MySQL doesn't include the charset at all and in previous versions Sequel Pro would also simply leave the field empty.

The grey means "This is the value, but is not configured explicitly".

Also this has been changed in development already: https://github.com/sequelpro/sequelpro/issues/2237#issuecomment-152902384

**Comment by stuconnolly** [comment]
Closing given the explanation and the changes made under #2237.
