### ISSUE TITLE
Command-delete (⌘-del) should delete highlighted row (like a file in Finder)

### ISSUE THREAD

**Issue by slater** [sequelpro/sequelpro#2333]

**Comment by samuelbradshaw** [comment]
In most apps where there is a list, like Mail for example, or bookmarks in Safari, you just have to press delete to remove something, rather than command-delete. Command-delete is only used for files in native apps. I don't think allowing command-delete to delete a row would be a problem, but I don't think we should remove the simple delete for deleting a row (I'm not sure if that's your intention, or if you just wanted both methods to be allowed).

**Comment by slater** [comment]
Sorry, yes, I meant that both methods be allowed :smile:
