### ISSUE TITLE
UI adjust: sorting

### ISSUE THREAD

**Issue by redolent** [sequelpro/sequelpro#2362]
Sorting is terrible on large tables. May I propose a fix?

Premise: when I want to change the order of a sort, I have to load the table data twice, which is painfully slow on large tables.

Solution:
1. Identify a table as 'large' (SequelPro kind of knows this already)
2. When sorting 'large' tables, wait 300ms (1/3 second) before running the query, to see if the user sorts the other direction.

How to reproduce:
1. Load a huge table with a large number of columns, and millions of rows
2. Sort by a column descending by clicking twice on a column heading

**Comment by dmoagx** [comment]
You can directly sort descending by doing a shift-click on the colum header.

**Comment by redolent** [comment]
Thank you. Maybe this could be added in the tooltip?

**Comment by sponno** [comment]
I don't think this issue has been clearly explained. 

1. On a numeric column eg, id.  The default display of ids is ascending which is fine.
![image](https://cloud.githubusercontent.com/assets/70642/13270395/c02276c4-daf2-11e5-987c-3e0eab2bfb5f.png)

2. Now if you sort this column with one click 
![image](https://cloud.githubusercontent.com/assets/70642/13270575/f68a8296-daf3-11e5-967e-4a804344eba9.png)
The table is now sorted, still in ascending order. Eg no change.

3. Now click a second time and the table is now sorted in Descending order.
![image](https://cloud.githubusercontent.com/assets/70642/13270598/1a21b274-daf4-11e5-901d-d8dea57c317a.png)

4. Sort again and its back to no sorting.

Could I suggest that the sorting cycle be changed from.
none (default, ID Asce) -> Asce -> Desc->none
to
none (default, ID Ascending)->Desc->Asce->none

**Comment by dmoagx** [comment]
The default is not ascending, but however MySQL has stored the rows.
This will only look ascending as long as your table has no significant fragmentation.
Here is a real-world example (3:1 insert:delete ratio):
![bildschirmfoto 2016-02-24 um 01 08 31 330](https://cloud.githubusercontent.com/assets/5793864/13271145/6015ddd4-da93-11e5-9f76-8ff819b28a6a.png)

**Comment by sponno** [comment]
The default display order for a table with auto inc primary index is ascending. 
The default display order foreign keys could be anything agreed.

But if you were are developer looking at 100s, 1000s or 10,000s or records. 
Do you want to see the latest insert, or record id 1? This logic applies to primary keys and foreign keys.

As the top commenter mentioned, he has to "double click" and also find that frustrating as I am 95% always looking for the most recent update and would prefer that the first sorting order request is descending.

P.S. I love this product and the team working on this! Yesterday donated $50 AUD, and I simply wanted to say thanks for a cool product. 

The second issue I found is a bit of pain, so I think I will jump into Xcode and submit a pull request : )

**Comment by abhibeckert** [comment]
@sponno No, the default is not primary index ascending, the default is MySQL's default sort order, which is based on the actual position of the data on your hard drive.

In some situations, MySQL will store the data on disk ordered by primary key, but there are many situations where it won't do that. For example, here's a screenshot of a table with only two columns, one of them the primary key and it's sorted descending:

![screen shot 2016-02-24 at 17 10 27](https://cloud.githubusercontent.com/assets/266088/13278112/89f95b40-db19-11e5-904f-9f2f85d1f16e.jpg)

The above is a MyISAM table. If it was InnoDB, then 444 would be the first row. Also, if I delete the `hello` column then even MyISAM would sort it by primary ascending. If the table had more than two rows, then I suspect the sort behaviour would be different again.

The default order of a table is very complicated.

The current behaviour is ideal, because not providing an "order by" statement guarantees fast query. Right now, we can almost always show the first page of table data in milliseconds. If we made it wort by primary key, then some tables would take minutes to load the first page.

However, needing to double click the primary key sucks. I think clicking on the primary key should do a sort desc instead of sort asc, since sorting desc is the most common for that column (other columns should default to sort asc as they do now.)

**Comment by dmoagx** [comment]
You don't need to double click. Shift+click also reverses the sort direction.

**Comment by abhibeckert** [comment]
I think shift click is too hidden for a problem so many of our users will face.
