### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by chadanuk** [sequelpro/sequelpro#2400]
Process cfprefsd starts on launch of sequel pro and along with sequel pro process hogs memory and doing anything that launches a new panel of sequel pro takes more than 5 minutes.

Could be due to OS X update? (v 10.11.3)?

I've not had any issues with this before.

![screen shot 2016-02-10 at 09 57 29](https://cloud.githubusercontent.com/assets/234815/12944030/bc27da76-cfdc-11e5-87d8-c6c4c86e5e23.png)

**Comment by dmoagx** [comment]
This sounds to me like you have a very large query in your query history. Try clearing it.

**Comment by chadanuk** [comment]
Thanks - that worked - I had to go into /Users/[username]/Library/Preferences and I had a couple of 1.8GB items that I had to delete in order to reset everything..

**Comment by clarkgaybel** [comment]
Just to report I had the exact same problem here. The application would consume all the memory, and would even eventually cypher all available space in startup disk because of swapping.

After reading this issue, I found I had 5 plist files of 1.6gb each.
It all originated trying to drag'n drop a 800mb sql file into the app for importing a database.

I would consider reopening this as a perf issue since not only it cant handle big queries that way, but it also has a huge impact on the overall system performance and there is no easy way to troubleshoot it.

**Comment by abhibeckert** [comment]
@clarkgaybel yeah, this is a known issue - we're using #687 to track it.
