### ISSUE TITLE
Don't specify "SET NAMES utf8mb4" without a conditional comment.

### ISSUE THREAD

**Issue by pnomolos** [sequelpro/sequelpro#2452]
Copied and slightly modified from http://www.heidisql.com/forum.php?t=20188

utf8mb4 wasn't available until MySQL/5.5.3 but SequelPro generates this on SQL dumps:

``` sql
SET NAMES utf8mb4;
```

... which leads to:

``` sql
/* SQL Error (1115): Unknown character set: 'utf8mb4' */
```

... on older servers. I guess it should be:

``` sql
/*!50503 SET NAMES utf8mb4 */;
```

... or maybe:

``` sql
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
```

... for some kind of backwards compatibility.

**Comment by dmoagx** [comment]
This is intentional.
Trying to import `utf8mb4` data as `utf8` could lead to data loss. 
Using a conditional comment would make it a silent data loss, which is even worse.
Therefore this is unconditional, so the user actively has to choose the risky path.

**Comment by abhibeckert** [comment]
@pnomolos if your table is set to `utf8` in Sequel Pro's Table Info tab:

![screen shot 2016-03-22 at 19 25 46](https://cloud.githubusercontent.com/assets/266088/13947035/ed1636d0-f063-11e5-8add-abeb81726860.jpg)

Then the export will do `SET NAMES utf8`.

If it's set to `utf8mb4` then you will need to import it on a server that supports that encoding. Changing the encoding could corrupt the data, since MySQL's `utf8` encoding is terrible and only supports a tiny fraction of UTF-8 characters. Only `utf8mb4` gets it right.

**Comment by dmoagx** [comment]
What we could do, though, is detect the error message on import and show a more user-friendly warning.

**Comment by pnomolos** [comment]
All my tables were set to UTF8 and it still had "SET NAMES utf8mb4" though,
so if that's the intended behaviour then it's still a bug (with multi-table
export).

**Comment by dmoagx** [comment]
SP will use `utf8mb4` for exports whenever the exporting server supports it.
Trying to determine whether utf8 or utf8mb4 is needed for export based on the user selection is too risky.

(Reopening for my comment above)

**Comment by pnomolos** [comment]
OK, fair enough. Makes it really tricky when you have to export to a server
that doesn't support it, though. I ended up manually changing the directive
because I knew my data was safe.

**Comment by abhibeckert** [comment]
@dmoagx I tested and it didn't use utf8mb4?

**Comment by dmoagx** [comment]
It's only on master, not the 1.1.x branch.
Also it won't show up if your server doesn't support `utf8mb4`.
