### ISSUE TITLE
Affected Tables Highlight

### ISSUE THREAD

**Issue by NasserAlmanji** [sequelpro/sequelpro#2455]
Sequel pro, 

Would not be nice if Sequel pro shows the affected tables (highlight them), when a query, transaction or stored procedure is run?

This can help developers track changes to database when they go step by step in a large system.

Regards,
Nasser

**Comment by dmoagx** [comment]
I'm not sure I understand you.

Determining what might be affected by an arbitrary query would not only require parser support even beyond an AST level, it also becomes nearly impossible to say as soon as a stored procedure, trigger or UDF become involved.

**Comment by NasserAlmanji** [comment]
@dmoagx 
Thanks.

Now, I assume it is a difficult problem.

My idea is that if a stored procedure involves changing 20 tables , then if that stored procedure is executed. Sequel Pro GUI will highlight the affected tables (and then if different procedure is run, the highlighting changes and so on).

Maybe my little knowledge about how databases work made me think it can be done without complexity.

Nasser

**Comment by rowanbeentje** [comment]
Hi Nasser,

The problem is that Sequel Pro isn't executing queries itself - that's MySQL's role as the underlying database engine.  Sequel Pro adds a UI on top of it, and can only add support for a feature where the MySQL API/ABI exposes data to allow it.

(For some things we've also added custom parsing of queries etc to be able to add extra features, but in this case we'd have to have full understanding of all queries run, so we'd be rewriting the whole parser!  Very hard to get right...)

**Comment by NasserAlmanji** [comment]
Thanks @rowanbeentje 
I appreciate using Sequel Pro.
