### ISSUE TITLE
When a date is entered with just partial info, fill in the rest

### ISSUE THREAD

**Issue by samuelbradshaw** [sequelpro/sequelpro#2467]
I often have dates to enter in my database that are just a year and a month. It'd be nice if I could type, for example, "2016-02" and Sequel Pro would automatically update it to "2016-02-01." Currently, it updates it to 0000-00-00 if I don't put a date.

**Comment by abhibeckert** [comment]
Perhaps this would be better done with a bundle, since the current behaviour might be relied on by some people (AFAIK we just give the string to MySQL and let it decide what to make of it).

Working with dates is complex and bug prone.

This bundle would do what you want and properly show an error if you give it invalid data – just type the partial date and press `Control-M`.

![screen shot 2016-04-08 at 09 31 35](https://cloud.githubusercontent.com/assets/266088/14369970/d0de7d0e-fd6c-11e5-9b10-a27b32c1a901.jpg)
