### ISSUE TITLE
Folders for tables/view

### ISSUE THREAD

**Issue by flashios09** [sequelpro/sequelpro#2491]
Hi,

Thanks for this awesome mac application 👍 
I want to suggest a feature :
Possibility to create folders to group tables/view

**Comment by dmoagx** [comment]
This is a duplicate of at least #402, (partly #582), #1037, #1800 and another one I can't find anymore because the merging info got lost during Google Code -> GitHub migration.

**Comment by flashios09** [comment]
@dmoagx i know it's DUPLICATED but i can't find an answer of this request ! that's why i create a new ticket

**Comment by abhibeckert** [comment]
@dmoagx #402 isn't a duplicate, it's asking us to implement a weird phpMyAdmin convention that I'm pretty sure is disabled by default and for good reason since it's not compatible with common table naming conventions

#582 is about databases, not tables

#1037 and #1800 are the same issue, but they were closed 3 years ago and should be reconsidered, especially since this would tie in well with #2480 which also requires attaching metadata to tables somehow.

**Comment by dmoagx** [comment]
#402 is the only option I see without storing additional metadata (which I'm totally against) and most of the time it will probably be only people wanting to group their `wp_*` tables from their `cms_*` or whatever tables so I consider that the easiest solution.

**Comment by abhibeckert** [comment]
@dmoagx I don't see any problem with saving it as part of the connection favourite. I wasn't thinking of actually storing anything in the database.

**Comment by dmoagx** [comment]
The problem I see is that, as soon as we add something like that, we'll get requests to make it shared for teams or users with multiple devices.
So we'll either have to start storing metadata in the DB or we'll have to redesign the favorite storage  to support sharing (#2502).
