### ISSUE TITLE
Query panel

### ISSUE THREAD

**Issue by hatchjt** [sequelpro/sequelpro#2498]
Really would love to have a query panel that can be open at the same time as the content or structure views. I often have to open the same database in two windows so I can see both simultaneously.

**Comment by Allendar** [comment]
I have this a lot too, but you have to take into consideration 2 kinds of ways OS X apps are build. Some apps (especially older ones) have this massive old-school windows over windows style of working. Others focus all logic into 1 main window with some (log/info) windows.

As opening multiple connection to a database (unless you have stone-age hosting with weird connection restrictions) shouldn't hurt. Because all modifications in MySQL are through queries, having 2 sessions open wouldn't really affect anything between the two windows. So you wouldn't really lose anything session-wise or environmental wise in both.

One last note; I sometimes do set globals specifically for a session, which I have to agree is something I have to redo for every window I open. Even tho I have these instructions in a Favorites entry it would be cool to actually give specific Bookmarks startup commands which will always be executed on opening them. For example opening a connection to Database1 normally and Database1 slow_query enabled mode, etc.
