### ISSUE TITLE
VIEW exported as TABLE

### ISSUE THREAD

**Issue by zette** [sequelpro/sequelpro#2556]
What steps will reproduce the problem?
1. Create a DB with a VIEW.
2. Export SQL file using Sequel Pro.
3. Import SQL file.

What is the expected output?
Expected to see it import the file without errors with original schema reproduced.

What do you see instead?
VIEW is not created and there are errors during import. In SQL file DROP is made on VIEW, but then TABLE with VIEW name is created.

What version of Sequel Pro are you using?
1.1.2 Build 4541

What version of OS X are you using?
Mountain Lion 10.11.6

What version of MySQL are you connecting to on the server?
MySQL 5.6.27

Statement in exported SQL dump:
```
DROP VIEW IF EXISTS `stacja_search`;

CREATE TABLE `stacja_search` (
   `id` BIGINT(20) NOT NULL DEFAULT '0',
   `provider_id` BIGINT(20) NOT NULL,
   `full_text` MEDIUMTEXT NULL DEFAULT NULL
) ENGINE=MyISAM;
```

VIEW syntax exported via 'Show CREATE VIEW Syntax'  from context menu:
```
CREATE ALGORITHM=UNDEFINED DEFINER=`stacja_int`@`%` SQL SECURITY DEFINER VIEW `stacja_search`
AS SELECT
   `parking_area`.`id` AS `id`,
   `parking_area`.`provider_id` AS `provider_id`,concat_ws(' ',`stacja_area`.`code`,
   `parking_area`.`name`,
   `parking_area`.`city`,
   `parking_area`.`region`,
   `parking_area`.`status`,
   `parking_area`.`notes`,
   `parking_area`.`bookkeeping_number`) AS `full_text`
FROM `stacja_area`;
```

**Comment by dmoagx** [comment]
That is by design.
Sequel Pro's SQL exports first create a surrogate TABLE for each VIEW, then once all tables are imported, replaces that with the actual VIEW.

Since you probably cancelled the import because of the errors, the SQL code to replace the table with the actual view did never run.

**Comment by hgrote** [comment]
I ran into a related problem today. When exporting/importing a table with large views, this approach can lead to an error "mysql row size too large", when the combined size of rows is >64K. 
In mysql this seems to be a hard limit on tables, but not on views.

One of my views combines many large varchar rows from different tables. So when the surrogate table gets created, it caused the error. This would not occur when the view would be created directly.

A possible workaround would be to minimise the size of the rows in the surrogate tables. That should be no problem, because no actual data gets imported to them (but maybe i'm missing something here).
