### ISSUE TITLE
How to use sequel pro for reverse ssh situations?

### ISSUE THREAD

**Issue by simkimsia** [sequelpro/sequelpro#2586]
cross posted on SO http://stackoverflow.com/q/39842691/80353

I have a server (I call this Mercury) behind a NAT that often requires me to go down physically to the network to troubleshoot.

I just discovered the concept of reverse SSH. So I intend to use a public server (I call this OWL) to allow me to SSH into Mercury.

Mercury runs a web app that relies on MySQL. I enjoy using sequel pro to administer the MySQL.

How can I use Sequel Pro and still use reverse SSH so that I need not go down every single time to the physical location to troubleshoot?

**Comment by willpower232** [comment]
I've done about three seconds of reading on it but is it not as simple as specifying "SSH Host: localhost" and "SSH Port: whatever port you used" on the SSH connection details page?

**Comment by Haravikk** [comment]
> is it not as simple as specifying "SSH Host: localhost" and "SSH Port: whatever port you used" on the SSH connection details page?

The purpose of reverse ssh is that you're actually causing the remote device to connect to you, rather than the other way around; this bypasses any incoming firewall restrictions on the remote server, since most NAT systems don't restrict outgoing connections.

In other words, if you have a client and a server, and the server's firewall (or network) blocks incoming SSH but the client's does not, then you can use reverse ssh to tell the server to connect anyway.

Looking at this guide I think it should be possible, but you'll need to run the initial command in terminal first: https://www.howtoforge.com/reverse-ssh-tunneling

`ssh -R 19999:localhost:22 <user>@<remote_address>`

Replacing the bracketed parts accordingly. Then in Sequel Pro's connection window you'd use:

**host**: localhost
**port**: 19999

Basically the `ssh` command creates a local ssh "server" which your remote machine connects to (bypassing its inbound NAT), you then connect to the same local server on the custom port specified (in this case `19999`). All authentication of the ssh connection is handled by the initial command, so you won't get convenient handling of that in Sequel Pro; all the usual ssh password commands should work, but recommend looking into passwordless ssh (using `ssh-keygen` to create a public/private key pair which acts as a password automatically) as this is much easier.

For completeness' sake though I should ask; can you not open any ports at all for your remote device? You mention physically going to the device so I assume it's on a local network; depending upon your firewall it should be possible to enable port 22 for ssh, but limit it to only local network addresses, i.e- no risk of connections coming from the internet. You can also use any port you like with SSH so long as you have control over the remote device to configure a custom port.

**Comment by simkimsia** [comment]
Thank you!
