### ISSUE TITLE
Can't Delete Rows in Query Results

### ISSUE THREAD

**Issue by IridescentShadow** [sequelpro/sequelpro#2596]
When running a query in the Query tab, there is no option to remove selected (or even single) rows in the results view. Pressing the delete key or backspace key doesn't do anything except make the system alert beep sound, there is no option for delete in the buttons at the bottom like there is in Content tab, and the right click context menu offers no delete option either. This is a huge usability issue.

**Comment by Haravikk** [comment]
I suspect this is by design, as the columns displayed in a `SELECT` query's results can actually be a wide range of things including the result of functions, grouped rows, a combination of multiple tables, variables, fixed values, sub-queries etc. etc. meaning there may not be a clear link between the result you selected and where it came from.

Working backwards from the results to figure out what it belongs to could get very complicated. I mean it's semi-feasible if Sequel Pro were to examine the columns, look to see if they corresponding to primary keys on a referenced table, and then perform a delete from there, but it would fail in a lot of cases.

The real question here is what are you doing with the query that you want to delete some of the results? If it's a simple query then you can just enter it as a filter in the contents view (the advanced filter can accept more complex queries too) and delete from there.
