### ISSUE TITLE
Inconvenient shortcut for console clearing

### ISSUE THREAD

**Issue by gekh** [sequelpro/sequelpro#2624]
Show console SHIFT CMD K
Clear console CMD K

Almost every day I clear console instead of see it. It's really annoying.
Please make another shortcut or give me option to change it. Ideal — disable "clear console" shortcut.

**Comment by abhibeckert** [comment]
What shortcut should be used instead of Shift-Cmd-K?

Safari uses Cmd-Option-C, however this is already being used by Sequel Pro for alternate copy/paste behaviour.

Cmd-K is the standard shortcut for clearing things:

![screen shot 2016-11-29 at 16 12 18](https://cloud.githubusercontent.com/assets/266088/20698708/abde95d4-b64e-11e6-81af-bdd705e77030.png)

However, it's probably a good idea to disable it unless the console is already open and has focus.

**Comment by lkg0dzre** [comment]
You know, often I press CMD K instead CMD SHIFT K, so I clear console before open it. I guess clearing is not need shortcut. It's rarely option and I can make it as context menu or top menu.

Also your console is more like log than terminal because I cant't execute commands. Yes, it's log, not console. There are no standard shortcut to delete log anywhere :)

I need console to find SQL queries and repeat it on production. So it's very important to me.
