### ISSUE TITLE
Updating Schema Impossible Because of Other Column 

### ISSUE THREAD

**Issue by WDC** [sequelpro/sequelpro#2630]
![image](https://cloud.githubusercontent.com/assets/1221004/21018553/46f98f2c-bd3b-11e6-9be6-c3deca2907e4.png)

I'm using Build 4749 (50a0f18).

The two columns in question are `last_login` and `created`, which seem to cause the error above when I try to `ALTER` any part of the table. In this case, I tried to add a column to this table, but I get an error for either `last_login` or `created`. Moreover, when I try to do *anything* to change those two columns, I get the same error about the other column (when I change `last_login`, the error cites errors with `created`, and vice-versa).

There is absolutely nothing related to those two columns, and I'm not sure why simply adding a new `INT` column causes such a error.

**Comment by dmoagx** [comment]
> and I'm not sure why simply adding a new INT column causes such a error.

Because you have MySQL strict mode enabled and `0000-00-00` is not a valid date.
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict

You can't fix that using the Sequel Pro GUI (unless you disable strict mode) as you would have to change both rows at the same time, but Sequel Pro executes the change as soon as you leave the first row. This is a design choice for Sequel Pro and won't likely change.

Also IMHO this is a very specialized issue, so I don't see any need add code to work around that.

Your best choice is to simply run a query like this by hand:
```sql
alter table t1 change d1 d1 datetime not null, change d2 d2 datetime not null;
```

**Comment by abhibeckert** [comment]
@dmoagx would setting the default value to `NULL` fix it?

**Comment by dmoagx** [comment]
In MySQL: yes, but that would change the column definition (in the screenshot above NULL is disabled)
In Sequel Pro: no, because the real issue is that there are two invalid rows which need to be updated in a single ALTER query, while Sequel Pro always updates a single row only.
