### ISSUE TITLE
Reported query execution time is wrong

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#264]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=264
Reporter:key8...@gmail.com Date:2009-05-17 22:27:50 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Execute a fairly long query (about 1-2 sec)
2. Look at sequel-pro reported query time versus MySQL command-line query time.
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Expected: 1.7 sec (reported by MySQL command-line interface)
Reported: 183 ms (reported by sequel-pro)

<b>What version of the product are you using? On what operating system?</b>
0.9.5 (663)  Mac OSX 10.5.6

<b>Please provide any additional information below.</b>
Queries run against MySQL database table with 1M+ rows, using InnoDB engine.

**Comment by kevin91liu** [comment]
Hi there, I'm also running into the same issue. I'm using Sequel Pro 1.1.2, build 4541 (602e11a). 

`set profiling = 1;  
select * from foo;
show profiles;`

foo is a fairly large table, with ~160k rows. When I run `select * from foo;` I get the "running query..." popup box for about 2 seconds. At the bottom of Sequel Pro I see

![image](https://cloud.githubusercontent.com/assets/7102984/14398897/c1a62a00-fdb5-11e5-9bbd-8168a58b512d.png)

But I doubt the 70ms number given. When I do `show profiles;` I see the query taking ~2.4 seconds. In fact, when I do another query `select * from bar;` where bar is a table with only 1 row, Sequel Pro again says the query took 70ms, whereas `show profiles;` says that it took 0.0004 seconds.

So what's the meaning of the time given by Sequel Pro?

**Comment by dmoagx** [comment]
This is what Sequel Pro reports:
```objc
		uint64_t queryStartTime = mach_absolute_time();
		queryStatus = mysql_real_query(mySQLConnection, queryBytes, queryBytesLength);
		queryExecutionTime = _elapsedSecondsSinceAbsoluteTime(queryStartTime);
```

If a single row query takes 70ms that means your network roundtrip latency is around 70ms.

If a 160k row query takes 70ms that means mysql started delivering the first data of the result set <1ms after it received the query...

**Comment by kevin91liu** [comment]
I see. Thanks.

**Comment by dmoagx** [comment]
Or as a visual **approximation**:
![unbenannt-1](https://cloud.githubusercontent.com/assets/5793864/14399911/00a8c848-fdf2-11e5-8720-7e0496fd7ede.jpg)

**Comment by dmoagx** [comment]
as an interim solution I've changed the message reported by SP a bit so it becomes more clear what time we measured.

**Comment by fulldecent** [comment]
Recommending close as mostly solved.

**Comment by LewisJEllis** [comment]
I ran into this today and I think this is still an issue. I have a large query that gives a "running query..." box for several seconds and takes ~5-10s to run; doing it with profiling like @kevin91liu suggested returns accurate 5-10s duration reports, but Sequelpro reports 100-200ms.

Notably, the improvement in messaging by @dmoagx has never made it into a stable release; the latest 1.1.2 release occurred a few weeks before that fix in April 2016.

I don't know why this issue was closed, but I think there's still a potential improvement here. With the new wording it'll be clear that the time reported represents "how long did the client wait until getting something", but I would still like to also know "how long did the database server spin its wheels on this query" - I think that's what the user would expect to see by default. That's what the MySQL CLI reports, as well as every other MySQL GUI tool I've used.

**Comment by kevin91liu** [comment]
I think users are generally more interested in seeing information on "how long did the query take" (the orange bar in the diagram in https://github.com/sequelpro/sequelpro/issues/264#issuecomment-207645163), rather than "how long did the client wait until getting something" ("What Sequel Pro reports" in the diagram). 

May I suggest changing the UI so that it reports that number instead (or even the yellow bar, if that is easier to implement)?

**Comment by krunkosaurus** [comment]
Just came across this issue today while trying to debug server performance. Sequel pro says query takes 82.4ms while command-line mysql says 12.91 sec. Perhaps Sequel pro should report both timings.
