### ISSUE TITLE
Accept donations / bounties

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#2746]
There are MANY issues here.

Please recommend a bounty service (like Bounty Source or whatever) so that people can attach money to issue. Hopefully this will make you money and help focus contributions to this project.

Work plan:

- [ ] Consider a few bounty providers
- [ ] Choose the best one
- [ ] Update README.md

    > If you would like to post a bounty for any feature requests/issues, we recommend you to use `BOUNTY PROVIDER`.

**Comment by dmoagx** [comment]
We already discussed that in the past in #362.
Basically this is not going to work.
We will never get enough money to pay any decent freelance ObjC developer for fulltime development of a feature and on the other hand "money as an incentive" has pretty much been proven to not work (and often even having contrary effects).
If someone isn't willing to get familiar with the SP source code right now, $100 would hardly change anything about that. And for those people that are currently involved with SP the main issue is the amount of spare time available (or not), rather than money.

**Comment by stuconnolly** [comment]
Agreed, the issue here is time, not money. 

I also disagree with the number of issues being high, considering the project is nearly 10 years old. A lot of them are very specific feature requests that wouldn't appeal to most users and could be argued are never going to be implemented, so we're not talking about 743 bugs (of which 56 have been fixed and are pending closure upon being released).

There's definitely a need for the open issues to be reviewed to close of duplicates, those already implemented/fixed and/or no longer applicable.

**Comment by fulldecent** [comment]
I have been browsing issues and there are surely many ideas about how Sequel Pro could help different people. I would help recommend issues to close if there was a more concrete project plan document that describes what is in scope for this project and if maintainers were responsive to recommendations to close issues that are out of scope. 

As for bounties. If an issue is in scope, its fix is likely to be accepted and people will appreciate the effort then I have found that people will line up to make the contribution. Bounties is one way to show how much people will appreciate the contribution. 

Another way to address all three items is for project maintainers to update README to say "Here are five simple and five difficult issues that we hope new contributors can help with".

**Comment by abhibeckert** [comment]
@fulldecent

>  I would help recommend issues to close if there was a more concrete project plan document that describes what is in scope for this project

We have two active projects:

 * fix a few outstanding bugs and release version 1.2 - https://github.com/sequelpro/sequelpro/projects/2
 * refactor connection/threading model, make some UI changes, and most likely add basic PostgreSQL support, and release version 2.0 - https://github.com/sequelpro/sequelpro/projects/2

When 1.2 ships, we will create a 1.2.1 project and maybe also a 1.3 project, both of these would ship before 2.0.

> And if maintainers were responsive to recommendations to close issues that are out of scope.

Due to timezones (we have nobody on the team in America), it can take several hours or maybe a day or so to get a response.

But we keep an eye on the issue tracker all day long at our regular day jobs and every comment is read by at least a few of us. Simply comment on an issue you think should be closed, and if we agree we will close it. I know there are many old issues open that should be closed, but don't have time to go through all of them.

> As for bounties. If an issue is in scope, its fix is likely to be accepted and people will appreciate the effort then I have found that people will line up to make the contribution. Bounties is one way to show how much people will appreciate the contribution.

We don't have any problems prioritising issues. We read every comment on the issue tracker, every @ mention to twitter and keep an eye on crash reports. From these it is obvious which two or three issues are the of the highest priority.

We also don't need financial contributions. We receive more than enough donations, as listed here: https://sequelpro.com/donate

We are not going to adopt a bounty provider because we don't need any more money and every minute spent keeping track of bounties is a minute that could be spent working on Sequel Pro.

The best way to help the project is to use our [test builds](https://sequelpro.com/test-builds) and report any issues (both bugs and missing features) here in the issue tracker. If you want to get more involved, then you can comment on issues written by other people or send us a pull request.

> Another way to address all three items is for project maintainers to update README to say "Here are five simple and five difficult issues that we hope new contributors can help with".

We have six issues for 1.2 and eight issues for 2.0, detailed on our two projects: https://github.com/sequelpro/sequelpro/projects

You're welcome to send us a pull request adding a paragraph of text and link to that page in the readme.md file.

**Comment by fulldecent** [comment]
@abhibeckert Thank you, update for readme sent in https://github.com/sequelpro/sequelpro/pull/2747

This is good enough for now and addresses my concern.

Perhaps in the future this project may better explain its long-term vision/scope. But that is not an issue for today.

I have gone through issues #1 to #1000 and reproduced, left feedback or recommended close as appropriate.

**Comment by schmod** [comment]
Looking at the kanban board, it looks like #1235 and #2753 are the only things really standing in the way of a release.  Anything we can do to help push those along and/or make an alpha release to get people testing the other changes?

**Comment by dmoagx** [comment]
I don't think #1235 will necessarily be fixed for 1.2. On the other hand I'd like to have a fix for #2258 as it is a major source of crashes currently.
