### ISSUE TITLE
Connection to remote host via SSH and hostname 'localhost'

### ISSUE THREAD

**Issue by Shogun147** [sequelpro/sequelpro#2777]
Hi there,

I've found quite old but similar issue at https://github.com/sequelpro/sequelpro/issues/386, maybe isn't actual anymore or can be fixed.

The problem is that i'm trying to connect to database on a remote server via SSH connection, MySQL is set to bind only for **localhost** host name, which means that i can't use 127.0.0.1 for this.

Once i'm trying to set this host name, SequelPro(v 1.1.2) shows popup with:
> You have entered 'localhost' for a non-socket connection.
> To MySQL, 'localhost' is a special host and means that a socket connection should be used.
and option to connect via local socket or 127.0.0.1.

Is there any way how this can be avoid and allow connection to remote host with localhost as host name?

Any help would be appreciated!

**Comment by dmoagx** [comment]
No, there is no way to achieve this.
If your MySQL server is configured either with `--skip-networking` or `--skip-name-resolve` then there is no way to connect to it via Sequel Pro and appear to come from `localhost`.

Because in that case `localhost` means socket connection and that is not possible via SSH.
Very recent versions of OpenSSH support socket forwarding (see #2054).
However **both** the server and client must be running at least OpenSSH 6.7 for this to work and it can't be configured in Sequel Pro currently.

You manually have to open a SSH connection with socket forwarding and then connect to the local socket endpoint in Sequel Pro.
