### ISSUE TITLE
[REQ] Notifications when query finishes

### ISSUE THREAD

**Issue by fitnr** [sequelpro/sequelpro#2780]
It would be great to have a desktop notification that appeared when the query finished if the application wasn't in the foreground

Use case: I occasionally run queries that take 10-15 minutes in Sequel Pro. Currently, I tab back to Sequel Pro every minute or so to check on the progress, but that's tiresome.

Precedent: [Postico](https://eggerapps.at/postico/), a desktop app for Postgres databases, has this behavior, and it's great.

**Comment by dmoagx** [comment]
Sequel Pro has had this feature for ages and I'm pretty sure that is where Postico got it from, too (since the author also worked on Sequel Pro in the past).

![bildschirmfoto 2017-05-04 um 23 20 12 453](https://cloud.githubusercontent.com/assets/5793864/25725460/60c5255c-3120-11e7-9905-27d636a9c8f8.png)

Perhaps you have disabled it in Prefs > Events > Enable Notifications or in System Prefs > Notifications?

**Comment by fitnr** [comment]
So it does. I only looked in the system notifications. Thanks!
