### ISSUE TITLE
Patreon donations

### ISSUE THREAD

**Issue by yhoiseth** [sequelpro/sequelpro#2836]
Hi,

Thanks for the good work on Sequel Pro. Sorry for posting this donations-related request here. I couldn't find an appropriate email address to use.

I'd like to set up a recurring monthly donation using Patreon, but I'm [unable to find a relevant profile](https://www.patreon.com/search?q=sequel+pro).

Would it be possible for you to point me to or set up a Patreon profile?

**Comment by abhibeckert** [comment]
The relevant email is contact@sequelpro.com.

We don't want to use Patreon because it would be additional work for account keeping/tax purposes.

I'm planning to add support for recurring donations to our donation page but haven't had time yet.

If you like, I can manually setup recurring payments using either PayPal or credit card. Email us if you'd like to do this.
