### ISSUE TITLE
Program crashes when selecting results after "describe" command

### ISSUE THREAD

**Issue by VampDuc** [sequelpro/sequelpro#2873]
If I double-click into the "Field" column, the program seizes up and my only recourse is to force quit.

**Comment by dmoagx** [comment]
Cannot reproduce and description too vague.

Could be caused by a large number of DBs/tables on the server, though (as the - completely pointless - query when trying to edit a query result is `SELECT COUNT(1) FROM information_schema.COLUMNS where ... all values of the row ...` and information_schema has turned out to be very slow in some instances)

**Comment by VampDuc** [comment]
I was just using `describe table;` The table in question has 13 rows. 

The issue comes when you double-click into an result and type a character.

**Comment by abhibeckert** [comment]
Can't reproduce.

When I try to edit the result of a describe query, I get a "Field is not editable. Couldn't identify field origin [...]" message and the edit is aborted.

I wonder if it could be a server side issue. We will be less susceptible to server side issues when #2731 is complete.

**Comment by abhibeckert** [comment]
> Update: My sysadmin was able to kill the query. It was hung on "checking permissions".

@VampDuc in that case, you could have killed the query yourself using Sequel Pro with the `Database -> Show Server Processes...` menu item.
