### ISSUE TITLE
column contains _

### ISSUE THREAD

**Issue by carloast82** [sequelpro/sequelpro#2964]
Hi,
if  i try to filter a column that contains '_' it dosn't work correctly
the result is all rows of my table.

best regards

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by TrekkerUK** [comment]
This is because 'contains' is just doing a MySQL LIKE search, and _ and % are wildcard characters and need to be escaped. If you type \_ (backslash, underscore) into the search field it will work correctly.

SequelPro should really automatically escape these before it performs the search - it already does so for quotes (').

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month, closing.
