### ISSUE TITLE
Bug: UI: Favorites: The white colored text on highlilghted favorites which are a certain bg color is unreadable.

### ISSUE THREAD

**Issue by jspreddy** [sequelpro/sequelpro#3022]
## Context: 
When a favorite is selected, it highlights the text to white with a blue background. I am guessing this is default mac behavior.

## Bug:
When a favorite with a light background color is selected, the text still turns white making it unreadable. 

## Possible Fix:
It would be great if the favorite's text color is left at black so that the contrast between the text and the background can be maintained.

### selecting a favorite with no bg.
![select_1](https://user-images.githubusercontent.com/2302194/38165305-6a321b7c-34df-11e8-99a5-3b4a7947975b.jpg)

### selecting a favorite with a light bg.
![selected_2](https://user-images.githubusercontent.com/2302194/38165296-4fd57422-34df-11e8-8eae-b0ebe6965744.jpg)

**Comment by dmoagx** [comment]
I don't know how to solve this.
Before 10.10 this has not been an issue, because:
* Lucida Grande is a font that works well for non-retina screens
* Selected items were shown in bold
* There was a text shadow

None of that is the case for 10.10+ as a result of some terrible UI choices Apple made.

Going by WCAG rules the contrast ratio should be at least 4.5:1 for regular text and the only favorite colors that meet this requirement are Yellow+Black and Green+Black. Even then the contrast ratio should be closer to 7:1 given the tiny font size.

On the other hand I don't want to have a mixture of foreground colors or violate the default look for highlighted items (blue+white), so we maybe have to change where we draw the backdrop.

**Comment by jspreddy** [comment]
Can we not have a map of bg and text colors and use those for coloring the UI?

yellowBg -> black text
redBg -> White text

Highlighting the row does not need to change the color of the text within the pill.
