### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by anotherdevs** [sequelpro/sequelpro#3052]
Hi

I myself did donate to Sequel Pro back in March 2013. It took two and a half year before a new release was available.

On this page you can see some donations dating back to 2016: https://sequelpro.com/donate
Let's say all these people (781) donated $10, that's stacking up to: $7810.

I see a lot of donation requests, but no one actually shows what the money are spent on.

When I donated the money was sent to:

MJ Media
matt@mjmedia.com.au

That is the same person who has gone AWOL (https://github.com/sequelpro/sequelpro/issues/3034) for almost a year.

**Is the money being spent on this project or just supporting @mattlangtree?**

Ping: @stuconnolly, @dmoagx, @avenjamin, @abhibeckert

**Comment by jpike88** [comment]
@mattlangtree @stuconnolly @dmoagx @avenjamin @abhibeckert someone needs to step up and take charge asap, this is getting ridiculous!

https://github.com/sequelpro/sequelpro/issues/3034

**Comment by dmoagx** [comment]
@anotherdevs 
I don't have access to donation history or bank accounts so I can't answer that question.

**Comment by abhibeckert** [comment]
The main reason we need donations is to run servers. We receive more than enough for that obviously.

If we had enough donations, we'd love to hire someone to work full time on sequel pro, but we don't receive enough for that.

For a period I was working on sequel pro one day per week and taking a modest hourly rate out of the donations, but I'm not doing this currently. I'd like to start again... it's mostly a lack of time on my part stopping it rather than a lack of funds for the project.

We have occasionally made large purchases, such as hiring consulting firms to do artwork.

**Comment by abhibeckert** [comment]
Re Matt going "AWOL" he's still around but has a baby to look after and no free time. He has never received any money from sequel pro, he previously ran the paypal account and did all the programming/etc for the old website as well as maintaining it. I've taken over all of that now.
