### ISSUE TITLE
Completion is not instant

### ISSUE THREAD

**Issue by Sammers21** [sequelpro/sequelpro#3060]
When I'm typing something, it takes a few seconds for suggesting a completion.

ENV:

Mac OS 10.13.4
Macbook pro 15, 2017, 512ssd

**Comment by srleach** [comment]
Since nobody's come in for this - I thought I'd advise, it's not an issue. 

Head into the preferences and navigate to the Query Editor tab - there's a time delay field for how long the editor will wait before suggesting autocomplete options. It's set at a default of 1.5 seconds but you can nudge this down to as low as 0.5 if desired.

<img width="195" alt="screen shot 2018-06-29 at 11 16 48" src="https://user-images.githubusercontent.com/13541397/42087396-f28aeaf4-7b8d-11e8-8820-5c0ad40c2a98.png">

**Comment by Sammers21** [comment]
@srleach , thx
