### ISSUE TITLE
why not add a table switch tab?

### ISSUE THREAD

**Issue by x1a0xv4n** [sequelpro/sequelpro#3157]
in fact, nearly all of the database client support this function, it's convenient to users;

**Comment by dmoagx** [comment]
What is a "table switch tab"?

**Comment by JeffcottLu** [comment]
just like this…

[cid:DAD10A71-C645-4218-ADF1-A6692506797D]

在 2018年9月12日，上午4:39，Max Lohrmann <notifications@github.com<mailto:notifications@github.com>> 写道：


What is a "table switch tab"?

**Comment by dmoagx** [comment]
SP already has connection tabs.
What is different about your approach and why do you think it is better?

**Comment by JeffcottLu** [comment]
connection tabs…so if i wanna open another table (in order to switch), i have to create a connection one more time?

在 2018年9月18日，上午4:37，Max Lohrmann <notifications@github.com<mailto:notifications@github.com>> 写道：


SP already has connection tabs.
What is different about your approach and why do you think it is better?
