### ISSUE TITLE
I want to write a Sequel Pro clone

### ISSUE THREAD

**Issue by alexanderniebuhr** [sequelpro/sequelpro#3173]
Ok guys,

i just contacted the owner of this Repo. I am going to port SequelPro to ElectronJS (starting now).

My name is Alexander Niebuhr, and I am working actively as a Software Engineer @ Germany
We have a lot of Devs working with Macs, and SequelPro. But the inactivity of this Repo is killing the great Program.
With over 900 open issues and 30 not merged pull request, not working build Server etc. the Program is not very useful at this stage, and SequelPro is loosing people!!! Which is sad, because Sequel Pro is used to be the No.1 SQL-Client for the Mac.

I decided to port to ElectronJS, because this is the state of the Art to develop cross-platform Desktop Apps in 2018. Also this gives the possibility to extend SequelPro in the future. Many other DB Clients have some nice features, SequelPro would like to have. 

Well this does mean some we have to live with some points as well:

- I am going to rewrite SequelPro from Scratch (just copy "features" and "design" - well redesign)
- Some open issues might still exist in the new version, well we would have to make a cut and start new to collect Issues and PR
- etc.

If anyone has, any thoughts on this. Don't hesitate to answer right now.
Well can we get like a little survey with this fancy Github Emojis, if this port is wished by the community??

Cheers
Alexander

**Comment by Envo** [comment]
It was a great native app, and it was one of, or even the greatest feature of Sequel Pro. I can understand your intention, but basicly this is just a very sad news for the Sequel Pro, and for the native app's users... I think it's time to start looking up for something else, or I just stick with the v1 until it's works.

**Comment by alexanderniebuhr** [comment]
Well,

To be honest with the new ElectronJS Release you are not able to tell if the App is native or not (except looking at Code)

It feels the Same, so there is no point of staying with the broken Code from v1.

This will lose some Users, but having a broken Version 1 for Ages will lose some more Users. 

Cheers 
Alex

**Comment by alexanderniebuhr** [comment]
And to be honest with everyone. SequelPro v1 is not going to be fixed any soon. And if it will be fixed it will than take Again ages for the Next Release!

**Comment by cookiecavekeeper** [comment]
> Well, To be honest with the new ElectronJS Release you are not able to tell if the App is native or not (except looking at Code) It feels the Same, so there is no point of staying with the broken Code from v1. This will lose some Users, but having a broken Version 1 for Ages will lose some more Users. Cheers Alex
> […](#)
> Am 22.09.2018 um 18:36 schrieb Zsolt Szrapkó ***@***.***>: It was a great native app, and it was one of, or even the greatest feature of Sequel Pro. I can understand your intention, but basicly this is just a very sad news for the Sequel Pro, and for the native app's users... I think it's time to start looking up for something else, or I just stick with the v1 until it's works. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

In what way is the code broken? Yes there hasnt been a release in ages which is huge problem, but the master branch works great for the most part(the new macOS and MySQL versions beeing the major problems).

Wouldnt it be much easier to fix the issues, rather than _rewrite the **entire** app in another language_?

And when you say "i just contacted the owner of this Repo", you kinda seem to imply that the maintainers of sequel pro "officialy approved" your new version 2. Is that actually the case?

When a new user rewrites an app from scratch in a new language, it seems more like a new app inspired by the original, rather than a new version (or even a fork) doesnt it?

**Comment by dmoagx** [comment]
I have changed the title of the issue since if has obviously already caused confusion.

Also @alexanderniebuhr, you are free to publish whatever software you like, even a clone of Sequel Pro - there is no need to announce that here.
However I want to point out that the name "Sequel Pro" and the Sequel Pro icon (database pancakes) are not open source and governed by copyright law.
Only those with written permission by the copyright holder may use them.
So you should better not call your new product "Sequel Pro v2".

I will close this issue now, since there is no point of discussing other products here and the lack of releases is already being discussed in #3034

**Comment by alexanderniebuhr** [comment]
Well,

Firstly i didnt get an answer from the owner yet.

Secondly well this Software does not work with the new Software as mentioned. So i have to Decide use Working sequel or new supposed Software.

Thirdly it is better to fix than rewrite but then this Has to Happen! Not Leave approved pull request Open!

Cheers and Peace in Love Alex!

**Comment by alexanderniebuhr** [comment]
Well not going to discuss. There is a PR which is not changing any Code. It just adds a line to Readme, so that Build instructions are easier to understand. There is no reason in my eyes to not merge this. Well i accept your way. Thanks for your Time. For me this can be closed now and Rest in peace please.
