### ISSUE TITLE
No displayed error when using reserved word(s) in query

### ISSUE THREAD

**Issue by jean-jacques-B** [sequelpro/sequelpro#3309]
- Sequel Pro Version:1.1.2 (4541)
- macOS Version:10.11
- MySQL Version:5.7.18

**Description**
When using reserved word(s) in queries, nonspecific error message are displayed

**Steps To Reproduce**
1. use a wrong query with some received word, say: SELECT WHEN FROM TABLE
2.I don't get an error message like :WHEN is a reserve word

**Expected Behaviour**

**Additional Context**

**Comment by dmoagx** [comment]
It is not Sequel Pros job to validate SQL syntax and because of the many MySQL forks and frequent changes this would be a nightmare to maintain.

Sequel Pro will report the error messages MySQL sends (`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHEN FROM TABLE' at line 1` in this case).

If you feel that error message is not informative you should talk to MySQL about that: http://bugs.mysql.com/

**Comment by jean-jacques-B** [comment]
Hi dmoagx,
This makes sense.
After several months working with Objective-C I was slightly lost with SQL syntax.
Sequel Pro is a really nice piece of software.
