### ISSUE TITLE
Cancelling import of dump (created by Sequel Pro export) leaves database in broken state

### ISSUE THREAD

**Issue by jordanade** [sequelpro/sequelpro#3373]
- Sequel Pro Version: Build 5427
- macOS Version: 10.14.2
- MySQL Version: 5.7.22

**Description**
Cancelling the import of a dump created by Sequel Pro export leaves database in broken state and unable to process connections.

**Steps To Reproduce**
1. Import SQL file created by Sequel Pro's export
2. Hit "cancel"
3. Database is completely broken; typical error is "Table 'xxx' was not locked with LOCK TABLES"

**Expected Behaviour**
Export is designed to use transactions, OR at least database is left in functional state when cancelling, OR at least "cancel" pauses the import and warns the user about proceeding.

**Comment by dmoagx** [comment]
An SQL import is nothing more than executing a program.
That program can do pretty much anything it wants to the db and there is no way for us to know what exactly that is. On the other hand, transaction support in MySQL is limited to some very specific options.
So, no, there is no way to rollback a partial SQL import.

Also this is is not a valid issue description, since it contains no information we could use to analyse or fix the problem!

**Comment by dmoagx** [comment]
> MySQL said: Table 'alerts' was not locked with LOCK TABLES

That error message has nothing to do with the state of the database. It tells you that the current session holds at least one `LOCK` which needs to be removed.

This is to be expected when canceling an SQL import, since you aborted it before the `UNLOCK` statement could be executed.

**Comment by jordanade** [comment]
I see. So I would just have to disconnect and reconnect. Thanks for the explanation.
