### ISSUE TITLE
Forced window resize/re-rendering of crops content area/scroll

### ISSUE THREAD

**Issue by bubach** [sequelpro/sequelpro#3465]
- Sequel Pro Version:
- macOS Version: Mojave 10.14.4 but kind of irrelevant, bug since way before then
- MySQL Version: irrelevant

**Description**
When moving the sequel pro window between screens, sometimes the OS will force a resize/re-rendering because for example - one screen is larger, or the dock bar is visible on of them. In such cases, mostly when window was maximized on screen1, it will crop the top 10-20pixels, usually the filtering bar and first database table listing will be unreadable. Scroll is at top but still not visible.

**Steps To Reproduce**
1. Maximize window on one screen
2. Move it to another screen with smaller rendering area

**Expected Behaviour**
I expect the listing areas, for result and or tables to shrink, not to be cropped from the top - making certain UI features unreachable - such as filtering toolbar.

**Additional Context**
Bug has been there for at least a year, running nightly builds atm - but seems to be a real old one.

**Comment by Zmimmy** [comment]
I notice similar things, mine happens mostly when the Sequel Pro window is on an external monitor with higher resolution than my laptop and the laptop wakes from sleep.  I can also reproduce it by using a tool like Divvy to move and resize the window.  I am running the most recent nightly build. see below

![seqProResizeIssue](https://user-images.githubusercontent.com/20668756/58341937-aab1d800-7e0c-11e9-8c92-444cf375d893.png)

**Comment by efaves** [comment]
I've also been experiencing this issue. On my query tab/query panel, for instance, the first row I can see is row 5. 

MacOS Mojave 10.14
Sequel Pro Nightly Build 5446 (97c1b857)

**Comment by yu-ichiro** [comment]
I'm using [magnet](https://magnet.crowdcafe.com/) which is an util that resizes windows for you, but since I started to use the nightly builds (I wanted to use the dark-mode), it broke like above.
I think the problem going on here is exactly as the title, "Forced" window resize/re-rendering. Even if you are using a bigger screen as a sub-display, when you move the smaller window from the main screen to the sub-display, and use magnet's shortcut to make the window fill the screen, you still get the same problem, this time the other way.

![image](https://user-images.githubusercontent.com/6957492/61609286-91080200-ac90-11e9-863a-d99b31fe833b.png)

It doesn't happen when you resize the window by dragging the corner or using option-click on the full-screen button, inferring that forcing window resize (giving window size from outside) might be the cause for this (not sure)

**Comment by benpoulson** [comment]
Exactly the same issue for me too. Ever since High Sierra.

**Comment by benpoulson** [comment]
Still an issue.

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
