### ISSUE TITLE
The Big Forehead bug

### ISSUE THREAD

**Issue by bb-seamus** [sequelpro/sequelpro#3493]
- Sequel Pro Version: 97c1b85783 (Nightly)
- macOS Version: 10.14.4
- MySQL Version: (Affects all versions)

**Description**
I use Spectacle for window management and when I expand my sequel pro window, it gets... well... a big forehead. Resizing also has weird results sometimes, with some things being out of the window view.

**Steps To Reproduce**
1. Open Sequel Pro
2. Connect to a DB
3. Use a window manager to expand the window -- its something with programmatically changing the window size. Dragging from the corners does not have an effect. 

**Expected Behaviour**
It should not have a giant gap between the table tools and the icon bar.

**Additional Context**
Only happens on the nightly build for me.

<img width="1918" alt="Screen Shot 2019-06-25 at 11 36 38 AM" src="https://user-images.githubusercontent.com/5438324/60124688-0f7b8d80-973f-11e9-86d1-b79914bd7faa.png">

**Comment by benpoulson** [comment]
I was checking to see if anyone else was having issues like this... as soon as I saw your ticket name I knew that you were experiencing the same issue as me!

**Comment by craighooghiem** [comment]
Perfect ticket title. Been having the same issue ever since I switched to nightly builds to fix the close-tab-close-everything bug.

**Comment by gtclicksignal** [comment]
I've been experiencing the same issue with SizeUp (http://www.irradiatedsoftware.com/sizeup/), which leads me to think it's probably a problem with any window manager that programatically resizes the window.  The two most common cases I run into are making the window full-screen, and moving a full screen window to a screen of a different size (most noticeable when it's larger, but smaller is also bad).

I never saw any issue like this on the release version, but ever since switching to Mojave, I've had the same problem on every nightly build I've tried.

**Comment by viktormaar** [comment]
Having the same issue. Even worse, when resizing (with the window manager) from a bigger screen size to a smaller. In this case the "Big Forehead" is negative, so the top part is just can not seen. Have to quit and restart.

**Comment by benpoulson** [comment]
Still an issue.

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
