### ISSUE TITLE
Monospaced fonts not used in pop-up editor

### ISSUE THREAD

**Issue by gms8994** [sequelpro/sequelpro#3495]
- Sequel Pro Version: Nightly 5446
- macOS Version: Mojave 10.14.5
- MySQL Version: 8.0.16

**Description**
I've checked the "Use monospaced fonts" box, but the pop-up editor for fields is not using a monospaced font. I've also set the "MySQL content font" to a monospaced font, but it is also not being used.

**Steps To Reproduce**
1. Switch Content view to use the popup editor
2. Double click a field to edit it
3. Note that it's using a non-monospaced font.

**Expected Behaviour**
The pop-up editor should display content using a monospaced font when the "Use monospaced fonts" box is checked.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/50712/60441971-0fb7d500-9be6-11e9-9bd8-c66b8719cf46.png">

**Comment by italktocomputers** [comment]
The problematic code looks to be here:

https://github.com/sequelpro/sequelpro/blob/97c1b857832ce3478c6742839116d4b286c9474e/Source/SPFieldEditorController.m#L310-L324

What seems to be happening is the pref ```[prefs objectForKey:SPFieldEditorSheetFont]``` (at least for me and I suspect you as well) is equal to the value: ```AppleSystemUIFont```,  even if you select 'use monospaced fonts' in preferences.  Because  ```[prefs objectForKey:SPFieldEditorSheetFont]``` evaluates to ```true```, ```SPDefaultMonospacedFontName``` is never used as the font.

I'm not really sure what ```[prefs objectForKey:SPFieldEditorSheetFont]``` is used for.   Maybe a fallback font?  I'm thinking this may be a semantic error but would need to investigate some more.
