### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by rikdavis** [sequelpro/sequelpro#3507]
Guys,

The app seems to be prone to crashing when multiple connection tabs are in use. From what I can tell, it seems that the crash occurs upon the action of closing one of the open tabs.
If I had to stake a guess at root cause, I would venture that it has some association to the killing of the connection associated with the connection tab being closed.

If you could fix this, it would really reduce the accompanying frustration that comes with these crashes and the loss of any work that was underway when the crash took place.

I'm on a Macbook Pro (OSX - Mojave Ver: 10.14.5 (18F203))
CPU: Intel Core i7 2.6GHz
Memory: 16GB 2400Mhz DDR4
Graphics: Intel UHD Graphics 630 1536MB

**Comment by Hubertnator** [comment]
The thing is the nightly builds do fix some problems on Mojave, it's just that they are holding off of a release because... who knows? Because they just don't care? This software is almost unusable on Catalina so... I don't know.
 Here are some references:
[](https://github.com/sequelpro/sequelpro/issues/3385)
[](https://github.com/sequelpro/sequelpro/issues/3485)

If the developers recommend we use TablePlus, something is wrong. I am trying to make a 1.1.3 fork, but... well, we'll see. I'll link it if it's done.
I also recommend TablePlus.

**Comment by Hubertnator** [comment]
[My SP fork](https://github.com/Hubertnator/sequelpro)
Download SequelPro.app.zip and unarchive, and open SequelPro.app

**Comment by rikdavis** [comment]
Thanks Hubertnator. Does your fork address this particular issue, by chance?

**Comment by m4tthumphrey** [comment]
This has been a known (pinned) issue for [some time](https://github.com/sequelpro/sequelpro/issues/3116). The nightly builds do solve the problem. I am unsure why they have not released a hot fix.

**Comment by Hubertnator** [comment]
@rikdavis Partly yes, it does.
@m4tthumphrey They haven't done the fix because... I really have no idea. There have been several issues about the most significant I found was [#3385](https://github.com/sequelpro/sequelpro/issues/3385) but it looks like they just can't get along - literally they are slowly recommending we just alternatives. 

This software has potential. It's just that they can't get along, and I don't have the skills to use this potential.
