### ISSUE TITLE
I am using MacOs Mojave 10.14.6 and facing unexpected crash down of problem when closes any tab.

### ISSUE THREAD

**Issue by abhiabik** [sequelpro/sequelpro#3531]
I have been facing this issue from last 8-9 months. It happens when I open multiple tab/connections. Whenever I close any tab the whole application crashes itself disconnecting all the connected databases. But when I reopen the application again I get a pop-up window which I will attach as a screenshot with this message. 
I also tried to report the issue but failed. Please revert with the solution or any more information you need. 

<img width="910" alt="Screenshot 2019-09-09 at 11 42 41 AM" src="https://user-images.githubusercontent.com/46021999/64507027-320d5380-d2f7-11e9-9dff-81ca91c012f2.png">

**Comment by maprangsoft** [comment]
me too. i use the last version of Mojave
error on click select database.
------------------------------------------------------
**Crash log:**
------------------------------------------------------
Process:               Sequel Pro [1418]
Path:                  /Applications/Sequel Pro 2.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [1418]
User ID:               501

Date/Time:             2019-08-16 15:48:32.725 +0700
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Anonymous UUID:        16ED15F1-CF59-E7BE-4E3D-62353AE077F9


Time Awake Since Boot: 1100 seconds
------------------------------------------------------
**Console:**
------------------------------------------------------
9 Sep BE 2562 16:27:22: Found 4 crash files
9 Sep BE 2562 16:27:22: CrashLog: /Users/kirin/Library/Logs/DiagnosticReports/Sequel Pro_2019-08-16-154833_Kirins-iMac.crash
9 Sep BE 2562 16:27:22: CrashLog: /Users/kirin/Library/Logs/DiagnosticReports/Sequel Pro_2019-08-15-154041_Kirins-iMac.crash
9 Sep BE 2562 16:27:22: CrashLog: /Users/kirin/Library/Logs/DiagnosticReports/Sequel Pro_2019-08-16-154847_Kirins-iMac.crash
9 Sep BE 2562 16:27:22: CrashLog: /Users/kirin/Library/Logs/DiagnosticReports/Sequel Pro_2019-08-16-154758_Kirins-iMac.crash
9 Sep BE 2562 16:27:22: Picking CrashLog: /Users/kirin/Library/Logs/DiagnosticReports/Sequel Pro_2019-08-16-154833_Kirins-iMac.crash
9 Sep BE 2562 16:27:58: Sending feedback to http://log.sequelpro.com/submit
9 Sep BE 2562 16:27:58: Posting 91248 bytes to http://log.sequelpro.com/submit
9 Sep BE 2562 16:27:58: Connection failed
9 Sep BE 2562 16:27:58: Upload failed: Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnde
------------------------------------------------------
**Exception:**
------------------------------------------------------
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6000002489e0

(
	0   CoreFoundation                      0x00007fff499d52fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff740a5a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff49a4f106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff4997718f ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff49976b38 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff4bb78112 __NSThread__start__ + 1194
	8   libsystem_pthread.dylib             0x00007fff75a672eb _pthread_body + 126
	9   libsystem_pthread.dylib             0x00007fff75a6a249 _pthread_start + 66
	10  libsystem_pthread.dylib             0x00007fff75a6640d thread_start + 13
)

**Comment by NiklasWilson** [comment]
I have had this same problem for months. Thought Id check for an update that might fix this... Apparently this hasn't been updated in multiple years :(

**Comment by OgnjenPutnikovic** [comment]
Yup, this is at least a 1-year old issue – sorry bud :(

**Comment by Keydex** [comment]
Not an official solution, but use the latest test build which has already fixed this issue. @NiklasWilson @maprangsoft @abhiabik https://github.com/sequelpro/sequelpro/issues/3516
