### ISSUE TITLE
It would be nice be able to limit "dangerous" SQL.

### ISSUE THREAD

**Issue by rnhurt** [sequelpro/sequelpro#3562]
Sometimes I connect to "production" databases and I don't want to accidentally change anything.  It would be nice if there was a preference to allow only "safe" SQL queries (ie. SELECT).  

I've seen this in other SQL clients and it was a very nice feature.

**Comment by rubenjleon** [comment]
@rnhurt Ever think about just creating a second account (grant select) with read only privileges?  Use that to operate safely instead of relying on software to protect you.  When you need to make modifications, log in with the other account that has more privileges (grant select, insert, update, delete).
