### ISSUE TITLE
[Latest test build: 97c1b85783] GUI doesn't scale appropriately when window size is changed by an external program

### ISSUE THREAD

**Issue by MattB-wbm** [sequelpro/sequelpro#3563]
I'm using a program called BetterTouchTool that resizes windows for me using keyboard shortcuts.

When I resize the window I've noticed two bugs, the right side of the screen doesn't vertically scale properly (pictured), and the text fields for queries won't let me scroll to the top anymore.

To fix this I usually have to make a new connection window and scale the window manually.

![_MySQL_5_6_45__Supplements_-_Internal_FunnelData_ThankYouPages_and_Notes](https://user-images.githubusercontent.com/53354298/66770189-cecd8e80-ee6b-11e9-8a90-596c728c3fad.jpg)

Here's a more egregious example (data obscured by screen capture software, not part of the bug):

![_MySQL_5_6_45__Supplements_-_Internal_FunnelData_BackendFlows](https://user-images.githubusercontent.com/53354298/66770403-68953b80-ee6c-11e9-9013-3064bccb43be.jpg)

**Comment by dingo-d** [comment]
Happens to me too. I'm using nightly build 5446 (87c1b858) on macOS Catalina (10.15). I resized it using the Spectacle app and I got a huge gap on the top.

![screenshot](https://user-images.githubusercontent.com/8638515/66832912-1f6fe500-ef5b-11e9-9793-ac559c0c9c9d.jpg)

**Comment by alexclifford** [comment]
Since Catalina I too am seeing a resizing issue when using Spectacle in the latest nightly build. For me it's the quick connect / favorites bar that doesn't size correctly:
![image](https://user-images.githubusercontent.com/184942/67053698-d9e72e00-f18d-11e9-9f91-a1beda082af5.png)

@dingo-d in Spectacle your issue is solved for me just by going Fullscreen (Spectacle not macOS native) and then Cmd+W Cmd+N to recreate the window. This obviously isn't ideal if you already have open connections, but I do this before beginning work.

**Comment by dingo-d** [comment]
Kinda fixes it, but opens it up on my laptop instead of my extended screens.
