### ISSUE TITLE
Closing a Sequel Pro window on Mac crashes app

### ISSUE THREAD

**Issue by AntonyPritchett** [sequelpro/sequelpro#3567]
Running Sequel Pro 1.1.2 on Mac Mojave

This issue has been happening for some time.

When I have multiple windows (connections to different databases) open, and I close one of them, the whole app crashes. I need to open the app and reopen any connections.

**Comment by nhoon2002** [comment]
This is an ongoing issue with the 1.1.2 build of Sequel Pro (see pinned issue).

I think the problem is that 1.1.2 is several years old.

I had this problem too and lived with it for a year until I decided enough is enough and upgraded to one of the more recent builds. 

https://sequelpro.com/test-builds
