### ISSUE TITLE
Make a new release. The most recent release (1.1.2) is over 3 years old and very buggy.

### ISSUE THREAD

**Issue by nhoon2002** [sequelpro/sequelpro#3580]
A lot of people have run into issues because the most recent release is from 2016. Please release a stable version that fixes some of the most common issues (like Mac crashing on close tab)

**Comment by mbahcoding** [comment]
Yeah, Love this software. Hope they release new stable version soon...

**Comment by jroszkiewicz** [comment]
I think project is dead :(

**Comment by wedi** [comment]
There are nightly builds available: https://sequelpro.com/test-builds

**Comment by nhoon2002** [comment]
@jroszkiewicz Not true at all! like @wedi said, there is constantly new features being tested and added. But really, they should just hit the checkpoint and make an official release so people aren't led to downloading a broken build from 3 years ago

**Comment by thomasgriffin** [comment]
Done is better than perfect.

**Comment by mbahcoding** [comment]
I've try some nightly build. I think its good enough. why dont throw to official stable release?

**Comment by teunis90** [comment]
I'm for a long time on Build 5446 (97c1b857), there are some quirks but this is still the best SQL viewer/editor on OSX. I'm in favor of pushing this version as the new stable.

Since the major Catalina update, there is a very annoying bug (#3584) that the sidebar consumes 50% off the window. However, how much I like to see that one resolved, that bug is on both the current stable and the nightly build mentioned.

**Comment by teunis90** [comment]
Not stale!

**Comment by stychos** [comment]
@teunis90 https://github.com/Sequel-Ace/Sequel-Ace

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
