### ISSUE TITLE
Build Failing with Xcode 11.2 with 3 errors

### ISSUE THREAD

**Issue by itcentralstation** [sequelpro/sequelpro#3587]
- Sequel Pro Version: Latest/Master
- macOS Version: Mojave - 10.14.6 
- MySQL Version: Never got that far because the Build failed.

**Description**
I am getting 3 errors while trying to build in Xcode 11.2(11B52)

1. The specified item could not be found in the keychain.
2. Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
3. Command CodeSign failed with a nonzero exit code

**Steps To Reproduce**
1. cloned to my local machine
2. Clicked on `sequel-pro.xcodeproj
3. In Xcode, clicked on the Build and Run button.

**Expected Behaviour**
The project should build and sequel pro should run.

**Comment by xdzhudx** [comment]
I encountered the same error.

**Comment by pixelit** [comment]
I have the same problem.

**Comment by 10gic** [comment]
If you don't care about sign, you can just open sequel pro in (please replace xxxx/yyyy ):
/Users/xxxx/Library/Developer/Xcode/DerivedData/sequel-pro-yyyy/Build/Products/Debug/Sequel Pro.app

**Comment by fabzzap** [comment]
I am having the same error. `/Users/xxxx/Library/Developer/Xcode/DerivedData/sequel-pro-yyyy/Build/Products/Debug/Sequel Pro.app` exists, so I can run it. However, debugging within Xcode is not possible, because Xcode's Product/Run command fails due to the signing problem. Is there a way to run Sequel Pro within Xcode's debugger?
