### ISSUE TITLE
[REQ] Multiple RDBMS support

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#362]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=362
Reporter:brandon....@gmail.com Date:2009-08-08 08:10:32 Status:Accepted

With the changes from 9.5 to 9.6, Sequel Pro is nearly flawless, and absolutely awesome.  It is by far 
my program of choice, but sometimes I have to deal with other RDBMSs, and I have to use some 
second- or third-rate tool (which is usually not free).   (I've used some tools that have more features 
than Sequel Pro, but they're usually ugly and non-intuitive, probably designed for full-time DBAs, 
not for developers.)

The name change from CocoaMySQL to Sequel Pro leaves open the possibility of supporting 
databases other than MySQL.  Of course you probably want to wait until after 1.0 to consider doing 
this, but what about supporting SQLite and PostgreSQL?    A lot of developers use SQLite locally, and 
quite a few seem to be moving to Postgres.

I realize this feature belongs on the backlog, and not something to be done right away, but please 
consider adding it.

**Comment by pratik60** [comment]
Psequel looks the best bet for a PostgresSQl GUI client atm. Development is active as well. 

http://www.psequel.com/

**Comment by euskadi31** [comment]
:+1: SQL Server
:+1: PostgreSQL

**Comment by jeremylivingston** [comment]
+1 for Postgres

**Comment by jCrip** [comment]
+1 for Postgres

**Comment by alexsun** [comment]
Thanks for awesome tool!
I have a little spare time, but a bit of knowledges in Objective-C, C/C++, developing for desktop too. Can writing stuff for Web, before is PHP, now Ruby (overall more half a decade), actually like a continue learning, looking for mentor, any collected or helpful information. Interest in implementation Postgres (SQLite too ) in Sequel. Possible take some parts or ideas from pgAdmin? (both tools are C based)
thanks again

**Comment by Jellyfrog** [comment]
I wonder if @stuconnolly would be interested in continuing his work now that PGClientKit is back alive again, maybe @djthorpe would like to help?

**Comment by dmoagx** [comment]
@Ahti (see #1260 for the question):

Sequel Pro doesn't separate Model and UI very well, meaning, right now the UI code is pretty close to the SQL generation and both is pretty much specific to MySQL.
So the hard part (and probably why this issue hasn't seen much activity) is not to add support for a new RDBMS, but to design an interface layer (OOP, not UI) and refactor MySQL out of the core. 

That is pretty much a mammoth task and right now it is missing an agenda we could work along.

The basic application model right now:
```
  Sequel Pro        SQL statement generation 
      |              and query handling, UI
      v
SPMySQL.framework   C/ObjC API bridge
      |
      v
 libmysqlclient     C-Level MySQL API
```
What we need:
```
  Sequel Pro        UI handling
      |
      v
     ???            SQL statement generation
      |              and query processing,
      |              DBMS feature information API
      v
SPMySQL.framework   C/ObjC API bridge
      |
      v
 libmysqlclient     C-Level MySQL API
```

**Personally** I still believe it is a bad idea to make Sequel Pro multi-RDBMS.
The definition of "schema" alone is a totally different thing between MySQL, Oracle and MSSQL.
All three require a totally different approach to this stuff, which in the end means either not supporting any RDBMS particularly well or moving so much code (including UI) into different submodules that Sequel Pro would be pretty much an empty shell.

**Comment by halilim** [comment]
@dmoagx what do you think about PostgreSQL? It's pretty close to MySQL (though I don't know the bounds of the context you define closeness in terms of Sequel Pro architecture). I'd venture to guess many people would be happy to have a MySQL and PostgreSQL only Sequel Pro.

**Comment by dmoagx** [comment]
I don't have any experience with Postgres, so I can't answer that.

Here's an example though:
MySQL "database": == schema. The object containing tables, views, stored procs, …
Oracle "database": == server instance. Each server instance can have multiple schemas.
MSSQL "database": == container for schemas within a server instance. Each instance can have many databases and each database can have many schemas.

MySQL "user": Unique via (username + connecting host), managed on server instance level.
Oracle "user": == schema.
MSSQL "user": Permissions applied to a "login" on the db level. Logins are managed on the server instance level.

**Comment by jopotts** [comment]
A Postgres only fork gets my vote. Strip it right back to the bare essentials just to get the project off the ground. I'm guessing that all most of us really want is the nice query editor and results table. All the rest is a bonus.

**Comment by Ahti** [comment]
Looking at @dmoagx example (and I am sure there are many other subtle and not so subtle differences) a potential layer to abstract all those differences away looks like it can't possibly be worth the effort.

So let's take a step back here, and think about why we want SequelPro to support other SQL-implementations (in my case that is SQLite):

* having a consistent interface: I switch between server-side and client-side development quite often, and thus from MySQL to SQLite. I'd love to view/query/edit both in a consistent interface
* having a nice interface: imho, SequelPro does a very good job displaying table schemat, contents and query results. While that seems like a minor thing (just use a table and slap everything in there, right?) I have seen other editors do it horribly wrong.

Now, this is only me, and I am not a heavy user nor expert in MySQL and SQLite, so ymmv.

But what I think may apply to other users is that the wish to have SequelPro support other SQLs is mainly due to the great UI.

So what if, instead of jamming all backends into one application, we approach the problem from the other direction: Take the important UI components like the table contents, query editor, schema view, search bar, ... and abstract them to a point where they get their data, and information about nomenclature, possible data types, lists of tables and fields (for the query editor), etc, ... from delegates/data sources.

These components could make the job of implementing a decent database viewer/editor for other backends much easier. SequelPro would still not support other backends, but if someone wants a SQLite version, he doesn't have to spend time making sure the major UI components work great, but can focus on providing data to those components, and building additional UI that is specific to SQLite.

**Comment by djthorpe** [comment]
I just wanted to comment since I was added into this conversation, and as the author of PostgresKit (https://github.com/djthorpe/postgresql-kit)...at a cursory glance, looks like there would be some work in order to abstract the code so SequelPro can work with other database servers, and I am focussed at the moment in trying to get V1 out of my framework! There are other alternatives for PostgreSQL (ie, https://eggerapps.at/postico/) which appear to be good.

**Comment by jwg2s** [comment]
Would also love to see SequelPro support Postgres!  I used SequelPro for ~2 years before having to switch to Postico (also a great app, but not quite as robust as SequelPro). :+1:

**Comment by lichtamberg** [comment]
how is the status of the postgres integration? Would love to help, but I have no idea of this programming language... So I just can wait :(

**Comment by brandondrew** [comment]
On Wed, Jun 10, 2015 at 10:54 AM, lichtamberg <notifications@github.com>
wrote:

> how is the status of the postgres integration? Would love to help, but I
> have no idea of this programming language... So I just can wait :(


@lichtamberg:
Judging from the history of this discussion, it's not likely to happen.
You're better off just finding a decent PG-focused app.


-- 
Brandon Zylstra
brandon.zylstra@gmail.com

**Comment by abhibeckert** [comment]
@brandondrew if it "wasn't likely to happen" we would have closed this issue or at least set the priority to low.

Work has already begun on Postgres integration. But it's a large undertaking and everybody on the team chooses what and when they work on things, so progress can be slow on anything that's not a serious bug.

**Comment by alexparker** [comment]
Good work sequelpro. I love you. Your work is IMMENSELY appreciated and I've been loving it for 7+ years. Thank you. PG integration does seem to be a huge undertaking especially at the quality that SequelPro operates at. So thanks for the update @abhibeckert

**Comment by ross-williams** [comment]
I keep hearing that PostgreSQL is more solid than MySQL
and I have an idea that I should move. However, I don't move
solely because SequelPro is so good, and development would
be much more difficult without it. For me, the perceived benefits
of PostgreSQL are smaller than the benefits of being able to
use SequelPro during development.

If SequelPro supported PostgreSQL, I would consider moving
to PostgreSQL.

**Comment by bassu** [comment]
@ross-williams There is an indirect alternative with some smart autocompletion that even SequelPro lacks at the moment. For data visualization `induction` is the best. Ever heard of [pgcli](https://vimeo.com/124125257) ?

**Comment by noma4i** [comment]
Any progress so far?

**Comment by RomainLanz** [comment]
It would be awesome to have PostgreSQL and SQLITE support in SequelPro.

You can use http://www.psequel.com to manage PostgreSQL database for the moment.

**Comment by ysmolsky** [comment]
I love SequelPRO! 
I look forward for support of PostgreSQL!

Thank you, awesome team of SequelPRO!

**Comment by abhibeckert** [comment]
This **_might_** happen as part of Sequel Pro 2.0. The roadmap for which is maintained here: https://github.com/sequelpro/sequelpro/wiki/Release-2.0

**Comment by RomainLanz** [comment]
:+1:

Also, is it possible to add the possibility to choose which columns you want to show/hide in the GUI? This will increase the performance of the NSTableView when you have a lot of data.

**Comment by abhibeckert** [comment]
@RomainLanz it's not possible but the next version is likely to handle large amounts of data better

**Comment by RomainLanz** [comment]
Good to read that! :+1: 

Thanks for your awesome work.

**Comment by tombusby** [comment]
I really, really hope PostgreSQL/SQLite support is added. The tools for those are all appalling.

**Comment by jwg2s** [comment]
@tombusby check out postico, probably the best client I've found so far

**Comment by euskadi31** [comment]
👍

**Comment by tombusby** [comment]
Thanks. I had a look at that, it looks really nice. I just resent the £30
pricetag.

**Comment by ulope** [comment]
Because $30 is such a ridiculous sum of money to pay for a tool that you're probably going to be using for years to come...

**Comment by tombusby** [comment]
£30 is more like $45, and I just don't feel I get that amount of value from
it when I have some crapper "good enough" free solutions.

**Comment by dmoagx** [comment]
# This is a issue tracker and not a discussion forum.
All comments that do not add value to the issue reported will be removed.

**Comment by harrislapiroff** [comment]
I'm extremely interested in this feature and would be willing to start a bounty on it at https://www.bountysource.com/. Does that seem like a good idea?

**Comment by abhibeckert** [comment]
@harrislapiroff please just make a donation via http://sequelpro.com/donate - the money does go towards development.

Having multiple sources of donation creates a ton of extra work on my end that would otherwise be spent actually working on Postgres. You can find a high level overview of our roadmap here: https://github.com/sequelpro/sequelpro/wiki/Release-2.0.

**Comment by harrislapiroff** [comment]
Okay, noted!

**Comment by dmoagx** [comment]
Kickstarter and co. have been discussed in the past:
https://github.com/sequelpro/sequelpro/issues/362#issuecomment-28114887

**Comment by abhibeckert** [comment]
I expect to have an experimental build supporting postrgres some time this year.

**Comment by gajus** [comment]
Has anyone been working on oracledb support?

**Comment by harrislapiroff** [comment]
@abhibeckert How are things going on this feature? Are there ways any of us can help? Is there a branch we can look at or contribute to?

**Comment by miketwalker** [comment]
@abhibeckert Any updates on the Postgres progress? Definitely the main feature I'm looking forward to seeing.

**Comment by abhibeckert** [comment]
@miketwalker not much progress to report sorry.

**Comment by affanshahid** [comment]
Is this no longer on the table?

**Comment by abhibeckert** [comment]
@affanshahid I'm currently working on changes that are a pre-requisit to this.

I removed the milestone tag a few months ago because we've stopped using milestones and are now using [projects](https://github.com/sequelpro/sequelpro/projects/3#card-2077319).

**Comment by abdulrahman-khankan** [comment]
What is the status of this? Is there any estimation on when (if ever) Postgres will be supported? 
Is it contributions problem? i.e. will more contributions help or it's more lack of resources (maintainers)?
Thanks!

**Comment by joaodlf** [comment]
At this point, I'm willing to pay for PG support in sequelpro. No other software comes close to matching it.

**Comment by lichtamberg** [comment]
[Postico](https://eggerapps.at/postico/) is a quite good psql app if you are looking for a replacement for sequel pro in the meantime.

**Comment by Tungtono** [comment]
[TablePlus](https://tableplus.io/) supports both Postgres and MySQL good enough tho.

**Comment by bjer** [comment]
I’m using Valentina Studio, took a while to get used to but it’s ok.

Cheers,
Eric

**Comment by geo-fk** [comment]
Surely someone has forked this and added the postgres support.

**Comment by webcoderkz** [comment]
This probably won't happen ever, TablePlus is quite good, or even DataGrip for jetbrains does it's work.

**Comment by rubenjleon** [comment]
It's amazing how fast, easy and intuitive Sequel Pro is.  Those other tools are functional but they kind of take time to get used to.  With Sequel Pro I'm running queries/analysis in seconds!  Love it.

**Comment by karimhm** [comment]
Why not just add [**OBDC**](https://en.wikipedia.org/wiki/Open_Database_Connectivity) support?, most databases support it.

**Comment by fuzzy76** [comment]
@karimhm please read through the issue before commenting. Nothing at all is added.

**Comment by tylerbenson** [comment]
I'd still love to see this implemented...

**Comment by fuzzy76** [comment]
@tylerbenson please read #3705 - Sequel Pro has been abandoned for a long time.

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705

Please open new Issue in new repo if you are interested in this feature.
