### ISSUE TITLE
The width of left pane is different every time sequelpro is opened

### ISSUE THREAD

**Issue by jnmdf** [sequelpro/sequelpro#3626]
<img width="1227" alt="图片" src="https://user-images.githubusercontent.com/34469581/71810153-a7721080-30ac-11ea-8111-909b0007a297.png">

The width of left pane is different every time sequelpro is opened, and finally the left pane is too wide. It is anonying.

version: 1.1.2
os: 10.15.2

**Comment by christatedavies** [comment]
Yeah, this is annoying. I've got the same issue and I'm on the nightly build (5446 - 97c1b857)

MacOS 10.15.2

**Comment by manomintis** [comment]
This is frustrating indeed. As for me, I don't need it to be wide, it is ok for it to be 1/6 or 1/5 of 13" screen width. Is there any chance the software could remember the width set by a user?

**Comment by DRP96** [comment]
> This is frustrating indeed. As for me, I don't need it to be wide, it is ok for it to be 1/6 or 1/5 of 13" screen width. Is there any chance the software could remember the width set by a user?

It usually does, it worked for me until upgrading to Catalina. There are probably some system changes and as Sequel Pro is currently not really being updated, it hasn't been adjusted to Catalina so far... The last release was quite a while ago.

This bug and a few issues with mariadb even made me (temporarily) switch to TablePlus.

I would be more than happy if these things would get fixed in near future. If theres a lack of developer capacities or motivation, I am pretty sure many people would be okay with paying for a good supported version of Sequel Pro!

**Comment by dpslwk** [comment]
Duplicate of #3581 and #3558, #3584
