### ISSUE TITLE
Is anyone ever going to update SequelPro???

### ISSUE THREAD

**Issue by JPeterson2015** [sequelpro/sequelpro#3701]
Is anyone ever going to update SequelPro??? It years out of date!

**Comment by Briones** [comment]
The last release was in 2016, I think it's safe to say that the project is abandoned. I use TablePlus instead:

https://tableplus.com/

**Comment by JPeterson2015** [comment]
@Briones That's cool. Looks similar but maybe even better??

**Comment by Briones** [comment]
It has the disadvantage of not being Open Source, and having limitations in their free version, but in other aspects seems to be updated often, and with a really nice GUI, it has also an iOS Version.

So at this moment is a good alternative, since here the discussion about if the project is dead or not, are going from years now.

**Comment by moioo** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
